### ISSUE TITLE
talk.js - August 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/talk.js#1]
## :calendar: Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/242410709/)
- [x] Date: 16 August 2017
- [x] Hosts: @jsstrn
- [x] Venue: PayPal Singapore, Suntec Tower 5

### :speech_balloon: Talks
- [x] Build a bot on NodeJS by Stacy Goh @stacygohyunsi 
- [x] Async programming constructs in ES2017 by Ying Ka Ho @yingkh 
- [x] Building a modular application with VueJS by Yong Jun @yongjun21 
- [ ] _You?_

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist
- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability with @realsoelynn
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by jsstrn** [comment]
@stacygohyunsi thanks for proposing your talk. I've added your talk for talk.js in August (date to be determined at a later time).

**Comment by yingkh** [comment]
**Title of your talk**
Async programming constructs in ES2017 - what's the hype?

**Talk description**
ES2017 is published this year and before the release there's been a lot of discussion on a new feature of ES2017 before its release - async functions. What's the hype of async functions in ES2017? I will explain the language constructs of async functions in order to answer the question and information related to the async function.

**Presenter**
Ying Ka Ho (www.github.com/yingkh)

**Presenter's bio**
Software engineer currently working in SME dealing with offline payments, with experience in async programming with C# for four years.  

**Duration request** 
20min

**Comment by jsstrn** [comment]
@yingkh thanks for your talk proposal.. see you in August

**Comment by yongjun21** [comment]
#### Title of your talk

Building a modular application with VueJS

#### Talk description

[Data.gov.sg](https://data.gov.sg) has recently released our *[SchoolPicker](https://schoolpicker.sg)* app, a geospatial data exploration tool to help parents and students find their ideal school. The app is built using VueJS, one of the fastest growing Javscript framework (62K stars on GitHub as of Aug 2017). We've learnt a lot about VueJS and its many supporting libraries (vuex, vue-router, vue-loader, vue-devtool...) in our journey of developing *SchoolPicker* and we want to share these learnings with the community. As part of our effort to promote use of open data, we are [open sourcing](https://github.com/datagovsg/school-picker) *SchoolPicker*'s code. This talk will also touch on how we designed *SchoolPicker* you can use our code to build similar apps for different use cases.

#### Presenter(s)

@yongjun21

#### Presenter's bio

To be updated

#### Duration requested

20min

#### Deck URL (if any)

**Comment by jsstrn** [comment]
@yongjun21 thanks for your talk proposal, see you at the upcoming talk.js

**Comment by jsstrn** [comment]
Hi @stacygohyunsi @yingkh @yongjun21 is 16 August 2017 (Wednesday) okay with everyone?

**Comment by yingkh** [comment]
@jsstrn I'm fine with it.

**Comment by stacygohyunsi** [comment]
It's fine with me thanks!

**Comment by yongjun21** [comment]
16 Aug is fine

**Comment by jsstrn** [comment]
Thanks @stacygohyunsi @yingkh @yongjun21 for speaking at talk.js. Closing this event.
