### ISSUE TITLE
🎙 talk.js - March 2018

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/talk.js#10]
### 📝 Details
- [ ] Event: [talk.js]()
- [x] Date: 21 March 2018 (Wednesday)
- [x] Hosts: @jsstrn
- [x] Venue: Microsoft, Level 21, One Marina Boulevard, Singapore 018989

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks
- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability with @realsoelynn
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by yosriady** [comment]
@jsstrn 

**Title of your talk**
Writing Domain Specific Languages with JSON Schema 

**Talk description**
In this talk, learn how you can use [JSON Schema](http://json-schema.org/) to write simple domain specific languages. You will learn about what Domain Specific Languages (DSLs) are, how the [WAML](https://waml.io/) web automation DSL was developed using JSON Schema, and the far-reaching applications of JSON Schema in other domains such as Headless CMSes and web applications.

**Presenter(s)**
[Yos Riady](https://yos.io)

**Presenter's bio**
Software craftsman based in Singapore.

**Duration requested**
20-30min

**Deck URL (if any)**
https://goo.gl/My9ABe

**Comment by ongmin** [comment]
=Edition Cancelled=
