### ISSUE TITLE
🎙talk.js - June 2018

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#11]
### 📝 Details
- [x] Event: [talk.js]()
- [x] Date: TBC (Probably 20th June)
- [x] Hosts: @ongmin
- [x] Venue: Singapore Power, #08-00 Keppel Tower 2, 240 Tanjong Pagar Road, Singapore 088540

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks
- [x] TensorFlow.js: Machine learning in the browser by _Alvin Chan_
- [x] Frontend Dependency Tracing for HTTP/2 Server Push by _Sophie Yang_
- [x] Automating processes using TagUI tool by _Ken Soh_
- [x] Building fast and semantic input masks in VueJS by _Divya Sasidharan_

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [x] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by cheeseprata** [comment]
Hi there, comments please :smiley: 

Title of your talk
TensorFlow.js: Machine learning in the browser

Talk description
TensorFlow, Google’s machine learning framework has finally arrived in Javascript!

Now you can create, train and run machine models in the browser. This means that data do not need to be transferred to a backend for prediction, and machine learning logic can be combined directly with your frontend magic in Javascript!

This talk will begin with a brief intro about machine learning for some context. Next, we will jump into code samples on how to create, train and run a machine learning model in the browser.

Presenter
[Alvin Chan](https://github.com/cheeseprata)

A short introduction of yourself
Full-stack developer, turned Data Scientist in cybersecurity startup. Starting PhD in Artificial Intelligence (NTU) this August.

Duration
20-30 min (depends on available time)

Deck URL
Coming soon..

**Comment by shortdiv** [comment]
## Talk Title
Building fast and semantic input masks in VueJS

## Talk Description
Forms are commonly notorious for having a poor user experience. When built well however, forms incentivize users to complete them quickly without sacrificing inaccuracies. Masked inputs are a key feature that enhances form design by giving the user feedback into the types of data being entered—whether or not the data is a credit card number, or a phone number for example. Though Input masks can be achieved via jQuery or plain JavaScript, they can be cumbersome and verbose to program. The template syntax alongside the state management system in VueJS offers a seamless solution to creating semantic web forms that also respond seamlessly to user input via input masks. In this talk, we will explore patterns and strategies to building semantic and robust input masks in VueJS and hopefully learn a thing or two about building things in Vue. 

## Presenter
Divya Sasidharan

## Bio
Divya is a web developer who is passionate about open source and good documentation. 

## Duration
10-15 minutes. The talk will be a demo of building form input elements using VueJS and will give a high level overview of how Vue works. 

## Deck URL 
TBD

**Comment by ongmin** [comment]
Hello guys! Thanks for the talk submissions, cool stuff. Unfortunately time is a little limited because we have 4 talks scheduled this month so lets work with the time allocations as follows: 

- @cheeseprata - 15 mins + 5mins Q&A
- Sophie Yang - 10 mins (TBD)
- @kensoh - 15 mins + 5 mins Q&A
- @shortdiv - 10 mins + 3 mins Q&A

Let me know if there's any issues! :) I can be reached via the Gitter group.

**Comment by ongmin** [comment]
@kensoh - Cool slides. Based on some experience, I recommend skimming through the reasoning behind this tool and focusing more on code demo (I see a 3mins video) and going more into the technicalities. That would be impactful and helpful. Feels like yours would be one that would benefit from keeping more time for Q&A out of the 20min block.

**Comment by ongmin** [comment]
@cheeseprata Hey, unfortunately we're running 4 talks this month so a 30 minute block would be tough. Let's try to keep the presentation to a 15mins and if you go a little over, that's cool (under 20 please, keeps the audience with you). Let me know if that works. Looking forward!

**Comment by ongmin** [comment]
@shortdiv :wave:

**Comment by kensoh** [comment]
Thanks @ongmin that sounds like a great idea! I'll do `@kensoh - 10 mins + 10 mins Q&A` 😃

**Comment by sophieyang0813** [comment]
**Title:** Frontend Dependency Tracing for HTTP/2 Server Push
**Description:**
I am working on a tool that automatically generates a resource manifest. I will talk about npm packages and the concepts (i.e. Abstract Syntax Tree, Visitor, and Walk) I learned from building this. As of today, this tool can parse html, css, and js files in my static portfolio directory and write out dependencies.  This project is inspired by [Server Push Cache Manifest: Eliminating round trip times at the HTTP/2 protocol level. ](https://www.youtube.com/watch?v=w1mlzgrSwew)

**Presenter**
Sophie  Yang 
**Bio**
I am a 6 months old baby coder and would love to share my learning experience.
