### ISSUE TITLE
talk.js - August 2018

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#13]
### 📝 Details
- [x] Event: [talk.js]()
- [x] Date: 29th August
- [x] Hosts: @jsstrn 
- [x] Venue: [Carousell](https://citymapper.com/go/7krcyk2vfo)

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks
- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [x] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by scboesch** [comment]
**Title**
Vue for Dad’s and Daughters: Starting simple and evolving towards best practices

**Talk description**
Vue is an open source javascript framework that recently passed React in the number of stars on Github. Vue enables you to develop your presentation layer in HTML rather than having to use JSX or plain Javascript. It is easy to start using Vue without a module system (no npm needed) and then switch to a module system in the future as projects get larger. In this talk, Shannon will demonstrate how to prototype in html and then begin adding Vue to make pages more dynamic. Chris will then discuss how to start modularizing your pages into components to make websites more maintainable, extendable, and testable.  

**Presenters**
Shannon and Chris Boesch

**Presenters' bios**
Shannon Boesch is a 15-year old high school student, artist, and avid reader. 
Chris Boesch is an Associate Professor, Education at NUS

**Duration**
30 minutes

**Deck URL**
TBD

**Comment by isaaclem** [comment]
#### Title
Object Oriented Design in VanillaJS

Talk description
In JavaScript we use a lot of objects, technically, anything that is not a primitive type, is an object in JavaScript. There are many design patterns in JavaScript and I'm going to share a few most common designs.

Presenters
Isaac Lem

Presenters' bios
Isaac is a software engineer at Detrack Systems

Duration
20 minutes

Deck URL
TBD

**Comment by yongjun21** [comment]
**Title**
The Work Behind [NDP Hunt](https://graphics.straitstimes.com/STI/STIMEDIA/Interactives/2018/07/ndp-hunt/index.html)

**Talk description**
Last month, Straits Times Interactive Graphics Team celebrated National Day by releasing our ”Find Wally” inspired NDP Hunt [game](https://graphics.straitstimes.com/STI/STIMEDIA/Interactives/2018/07/ndp-hunt/index.html). Within weeks, 21K readers have participated in our challenge of finding 53 hidden items. Find out how this interactive was build in under two weeks and learn how you can build your own interactive ”Find Wally” game too!

**Presenters**
Yong Jun

**Presenters' bios**
Senior Web Developer at Straits Times Interactive Graphics

**Duration**
20 minutes

**Deck URL**
Work in progress

**Comment by ongmin** [comment]
Hi everyone!

The topics and timing all look good. :) Just note that the Duration is inclusive of the 5 minutes for Q&A.
Jesstern will be the host for this meetup.

Have an awesome one!
Min

**Comment by jsstrn** [comment]
Hi @scboesch @isaaclem @yongjun21, please note that there's a change in venue. We'll be hosting tonight's event at Carousell. They are located at Keppel Towers 2 at 240 Tanjong Pagar Road #12-00 Singapore 088540.

**Comment by isaaclem** [comment]
@jsstrn : Thanks for the heads up, see you all tonight!

**Comment by scboesch** [comment]
@jsstrn : Thanks. We are looking forward to it.

**Comment by jsstrn** [comment]
Thanks @scboesch @isaaclem @yongjun21 for speaking tonight. Hope to see you at the next one.
