### ISSUE TITLE
talk.js - September 2018

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/talk.js#14]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/hpxdtpyxmbzb/)
- [x] Date: 26 September 2018
- [x] Hosts: @jsstrn 
- [x] Venue: AWS

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [x] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by amielperez** [comment]
#### Title of my talk
Observables are not (just) pub/sub: Exploring Reactive Programming

#### Talk description
I want to discuss Reactive Programming as a new programming paradigm that can change the way how we can view any programming problem -- not just those related to messaging -- and consequently change how we think about solutions, which will make heavy use of observable streams.

#### Presenter
Amiel Perez (@amielperez)

#### Presenter's bio
I am a front-end engineer doing my very best to keep up with the dynamic world of Javascript and front-end frameworks. I currently work for JP Morgan Chase, N. A.

When I am not coding, I would probably be drawing/painting, or would be found in the city area enjoying drinks with friends.

#### Duration requested
20 mins - there will be some code walkthroughs

#### Deck URL
Coming soon

**Comment by jsstrn** [comment]
Hi @amielperez 👋 Thanks for submitting your talk. Looking forward to your talk.

**Comment by nodes777** [comment]
**Title**
Top 5 Easy Ways to Make Your Site and Apps Accessible

**Description**
Web Accessibility is an imporant part of web development but is often looked over by developers and project managers. You can decrease liability and increase usuability by including some simple code and design decisions.

1) Images: Not Just Alt Text
2) Label Your Form Fields: Sorry, the Placeholder Attribute Doesn't Work
3) Keyboard Accessibility: Developers Don't Like To Take Their Hands Off The Keyboard, Why Would You Make Your Users?
4) Color Contrast: Paint With All The Colors of the Wind, But Ensure That The Foreground and Background Meet Contrast Standards
5) Semantic HTML: Or How I Learned to Stop Worrying and Override My Heading Element Styles

Conclusion:
Resources and Tools

**Presenter**
[Taylor Nodell](https://github.com/nodes777)
[taylornodell.com](http://taylornodell.com)

**Presenter's bio**
I'm a JavaScript developer focusing in accessibility. I write games in JavaScript and Unity as a hobby. Currently backpacking in Singapore as I look for a front end position.

If I'm not coding, you can find me running or making music.

**Duration requested**
10 mins - Short code examples

**Deck URL**
Coming soon

**Comment by ongmin** [comment]
Last Talk fort this month:

**Title of your talk**

Getting Started Building Serverless Data-Driven Web Apps using React, GraphQL, and AWS AppSync

**Talk description**

Since its release in 2015, GraphQL has risen in popularity as a compelling alternative to REST for developing APIs thanks to its network efficiency, client-driven design, and technical flexibility. But deploying a highly available and scaleable GraphQL server can be a challenge. In this session, we will build a small web app to interact with a simple event management GraphQL API, allowing users to view or create new events. We will cover the basics of using React to render a web app with AWS Amplify, AWS Amplify to provision and manage cloud resources, and AWS AppSync to host a secure and scaleable GraphQL endpoint on AWS with data backed by Amazon DynamoDB.

**Presenter(s)**

Gabe Hollombe @gabehollombe 

**Presenter's bio**

Gabe Hollombe is a software craftsman in Singapore and Technical Evangelist at Amazon Web Services

**Duration requested**

30 mins

**Comment by ongmin** [comment]
Talks for this month confirmed (all the 4 above) and full. 
Do pop your talks in for October's meetup instead: https://github.com/SingaporeJS/talk.js/issues/15

Thanks! :)

**Comment by amielperez** [comment]
Hi -- first time to present here at talk.js :) What equipment would be available to the presenters on the venue? I plan to bring a display port-ready laptop -- is that enough? Thanks!

**Comment by gabehollombe** [comment]
I think we have VGA / HDMI input. Display-port might work too.  Can you
bring a display port to HDMI adapter just in case?

**Comment by nodes777** [comment]
I'll be bringing a display port to HDMI as well.

**Comment by amielperez** [comment]
@jsstrn @ongmin @nodes777 @gabehollombe My sincerest apologies but I will have to regretfully withdraw from speaking in this event. Despite having my materials and code examples 100% ready, external factors prevent me from proceeding.

I will still be attending as a participant so I look forward to meeting you all, and possibly give more details.

Thank you.

**Comment by jsstrn** [comment]
@amielperez thanks for letting us know in advance. Feel free to speak at next month's session.
