### ISSUE TITLE
talk.js Nov 2018

### ISSUE THREAD

**Issue by khangtoh** [SingaporeJS/talk.js#16]
It looks like there is no event scheduled for Nov and I have a proposal :)

My name is Khang, and I am the Facebook Developer Circles Lead for Singapore.
Developer Circles is a new program from Facebook, comprised of a global network of developer communities around the world. Driven by Facebook’s overall mission to connect the world, Developer Circles is a new program designed to connect developers to foster collaboration and knowledge sharing.

As the Lead for the Developer Circles here in Singapore organizing events, managing our online community of 150+members since launch, and liaising with Facebook as an overall advisor for the program.

I want to reach out to invite members of Talk.JS to our event on Nov 28th, and as a community partner to co-host the events for your members.

We are open for collaborating on future meetup events as well.

**Comment by khangtoh** [comment]
@sebdeckers There is only a FB event for now, a Splashthat event should be up soon. 
For November, we are focusing on the launch event. Future events can be hosted at FB, December might be a little tough to plan. 

In general, I have plans to co-host some of the meetups with other local dev communities.

**Comment by sw-yx** [comment]
ooh! im landing on the morning of nov 28th. would love to come check it out. what do we have to do?

**Comment by khangtoh** [comment]
@sw-yx If you want to speak, let me know, the event is Nov28th evening. Talk.JS just need to create a joint co-host event for Nov 28th and promote to the members.

**Comment by sw-yx** [comment]
well i cant speak for TalkJS but i'd be happy to speak if they're up for cohosting!

**Comment by khangtoh** [comment]
> well i cant speak for TalkJS but i'd be happy to speak if they're up for cohosting!

I think we have enough RSVP for now, so there's no need for TalkJS  co-host this event.
Let chat via Messenger? I've added you. :)
