### ISSUE TITLE
🎙 talk.js - March 2019

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#19]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS)
- [x] Date: 13 March (Wed)
- [x] Hosts: @timoxley @ongmin
- [x] Venue: Microsoft

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [x] Confirm date and venue availability
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [x] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [x] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by ckkok** [comment]
#### Title of your topic
Concurrency in NodeJS

#### Topic description
Why isn't JS more prominent in the world of AI/Machine Learning? On the server-side, NodeJS has fantastic I/O performance for a seemingly single-threaded computing model due to its ability to handle such tasks asynchronously. But this fails for CPU-bound tasks that block threads. Before the current NodeJS LTS version, computationally heavy tasks could be farmed out to child processes, taking advantage of multicore CPUs, but processes do not share memory and inter-process communication adds significant overhead. Multithreading support landed in NodeJS as of v10.5.0, and is currently still hidden away behind an experimental flag. With multithreading, it is now possible to process such tasks in separate threads with shared memory, but this power does not come for free. Here, we compare the implementation and performance of a multithreaded NodeJS web server with that of some other industry solutions. What are the challenges when multithreading NodeJS, and how does the performance gap look like now?

#### Presenter(s)
https://github.com/ckkok

#### Presenter's bio
Chee Kean is a software engineer from the Maltem Consulting Group. Although his day-to-day work currently uses enterprise Java, he used to build JS front-end e-learning applications and still uses NodeJS extensively for pet projects.

#### Duration
30 minutes

**Comment by ais-one** [comment]
#### Title of your topic

Using Nuxt generate for building static web applications

#### Topic description

NuxtJS is a framework for VueJS that helps in building applications in single page (SPA) mode or universal mode (SSR)

SPA apps can be easily deployed on cloud storage such as Google Cloud Storage, AWS S3, Now, Netlify but it takes time for the app to be loaded and SEO is a problem as there are no pre-generated content.

SSR apps address the issues of load speed and SEO but requires a backend server to server the pages.

So to get the best of both worlds. We use Nuxt generate. This talk will focus on the use of nuxt generate, its advantages, its pitfalls. We will also be looking at few things which one may need to take note of when using nuxt generate
1) handling dynamic routing
2) use of dynamically created Vuex modules

#### Presenter(s)

https://github.com/ais-one

#### Presenter's bio

Aaron is currently doing consulting work with Zenika Singapore. Using JS only for literally everything now...

#### Duration

20 minutes

**Comment by danielepolencic** [comment]
Happy to present my talk in March is there's still space https://github.com/SingaporeJS/talk.js/issues/21#issuecomment-470130937

**Comment by malgamves** [comment]
Ahh! I come into Singapore in 14th March would have loved to share my talk on building Realtime CRUD Apps with JavaScript and GraphQL..any other meetups planned for March?

**Comment by ais-one** [comment]
FOSSAsia is in March...

**Comment by malgamves** [comment]
Do they have something letting people apply to speak? @ais-one

**Comment by ais-one** [comment]
I think you can try and contact them if they have slots...

**Comment by ais-one** [comment]
I just realize it may be a bit too late to be speaker in FOSSASIA... The
problem is your arrival date is just after March talkJS...




*Warmest Regards,*

*Aaron*


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by ais-one** [comment]
submitting on behalf of @allanchua101, he will comment later...



#### Title of your topic

Proxy Pattern: Re-usable and Mockable API calls

#### Topic description

![whatsapp image 2019-03-07 at 15 16 26](https://user-images.githubusercontent.com/4284574/54008086-f9ea5400-419f-11e9-8e8b-eba3bfc50975.jpeg)

 
#### Presenter(s)
https://github.com/ckkok

#### Presenter's bio
Alan is a software engineer at Sleek, Singapore.
> 
#### Duration
20 minutes

**Comment by malgamves** [comment]
Hey that's not a problem. Maybe next time!

**Comment by ongmin** [comment]
@danielepolencic Hey, I'm so sorry but I missed your comment for this month!

**Comment by ckkok** [comment]
#### Title of your topic
Concurrency in NodeJS

#### Repository for examples that we didn't have time to see.

https://github.com/ckkok/nodejs-concurrency

**Comment by ongmin** [comment]
Video recordings of talks: 

Proxy Pattern: Re-usable and Mockable API calls by @allanchua101: [https://engineers.sg/v/3246](https://engineers.sg/v/3246)
Using Nuxt generate for building static web applications by @ais-one: [https://engineers.sg/v/3247](https://engineers.sg/v/3247)
Concurrency in NodeJS by @ckkok: [https://engineers.sg/v/3248](https://engineers.sg/v/3248)

Thanks again everyone! :)

PS. Checkout Microsoft learning resources at: [https://docs.microsoft.com/en-us/learn/](https://docs.microsoft.com/en-us/learn/)
