### ISSUE TITLE
🎙 talk.js - September 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/talk.js#2]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/242664834/)
- [x] Date: 20 September 2017 (Wednesday)
- [x] Hosts: @jsstrn
- [x] Venue: PayPal Singapore, Suntec Tower 5

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks
- [x] **The evolution of JavaScript asynchronous calls** by Pham Huy Hoang @conanak99

- [x] **Speed up your code reviews using ESLint and Prettier** by Shesh @sheshbabu 

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability with @realsoelynn
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [x] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [x] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by jsstrn** [comment]
@conanak99 Your talk has been scheduled for 20 September. Cheers! 😃

**Comment by conanak99** [comment]
@jsstrn  Just update my talk and slide url here :D

**Title of your talk**
The evolution of JS Asynchronous Call

**Talk description**
How we do asynchronous call in JS "the right way"
From callback and callback hell to ES6 promise, generator and ES7 async/await

**Presenter(s)**
Pham Huy Hoang - [https://github.com/conanak99](https://github.com/conanak99)

**Presenter's bio**
Senior Front-End Software Engineer at [Algomerchant Singapore](https://www.algomerchant.com/)
I'm interested in JS technology in both front-end and back-end. My favorite technologies are Webpack, React + Redux, ReactNative.

**Duration requested**
30min

**Deck URL**
https://goo.gl/YkEiLW (Draft done, might need some polishing)

**Comment by sheshbabu** [comment]
**Title of your talk**

Speed up your code reviews using ESLint and Prettier

**Talk description**

How we can make code reviews faster by automating certain aspects of it. Based on this [blog post](http://www.sheshbabu.com/posts/speed-up-your-code-reviews-using-eslint-and-prettier/).

**Presenter**

Shesh - https://github.com/sheshbabu, https://twitter.com/sheshbabu

**Presenter's bio**

Senior Frontend Developer @ [RedMart](https://redmart.com/). I love all aspects of building software - from product, ux, frontend, backend, devops and databases. When not programming, I like to experiment with different cooking recipes (which sometimes actually end up tasting good 😄).

**Duration requested**

~15min

**Deck URL**

Will add soon!

**Comment by jsstrn** [comment]
Hi @sheshbabu, thanks for submitting your talk proposal. Looking forward to your talk.

**Comment by sheshbabu** [comment]
Thanks @jsstrn! 👍
