### ISSUE TITLE
🎙 talk.js - June 2019 (JSConf.Asia Special)

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#23]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/261294292/)
- [x] Date: 12 June (Wed)
- [x] Hosts: @ongmin @huijing
- [x] Venue: Carousell

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

Talks are by invite for this month, but feel free to propose below!

<details>
<summary>Click for the Format to Propose a Talk</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [x] Confirm date and venue availability
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by AlexLakatos** [comment]
I'm in the area for JSConf.Asia, I'm giving a workshop there. I was wondering if I can do a talk here as well. I wanted to do "Hands-on Performance Debugging with the browser DevTools", it's "A no-slides, hands-on, live debugging session using only the browser Developer Tools on the website I pick from the audience. We'll dive deep into spotting performance bottlenecks into any website and how to fix them."

**Comment by ongmin** [comment]
@AlexLakatos Hey! That sounds awesome, sorry to edit your original comment (sooooo sorry, it does feel weird doing it, but I thought it could save some pingpong messages). I took the liberty to fill in some info in our talk details format based on what you wrote. It's how we keep track and organise them. :) Please feel free to edit and write whatever you think is suitable.

Thanks for offering to speak. :)

**Comment by AlexLakatos** [comment]
No worries, I think this is actually great, thanks for editing. I'll update now with the duration.

**Comment by ryzokuken** [comment]
**Title of your topic**

State of crypto in Node.js

**Topic description**

Cryptography is all around us, and that’s a good thing. In a world that increasingly depends on data, leveraging cryptography is mandatory for any modern application that deals with private user data.

As a Node.js core team member, I will focus on the current state of cryptography in Node.js regarding security, interoperability and performance: What has happened, what is about to happen? What are our long-term plans?

Node.js is made for the web and already well-equipped for the challenges of cryptography in today’s applications! You will come away with a deeper understanding of some of these challenges and how to solve them using the Node.js crypto module (and how not to!).

**Presenter(s)**

Twitter and Github and literally everywhere else: @ryzokuken

**Presenter's bio**

Ujjwal is a Node.js core collaborator, Electron maintainer, Google Summer of Code mentor and ex-student. An international speaker and a JavaScript/C++ developer, he has been working with the V8 team and the TC39 committee to help make JavaScript better, one commit at a time. He loves to talk about open source software, DevOps, JavaScript, Web Standards and the Open Web.

**Duration**

30 minutes

**Comment by hanlindev** [comment]
#### Title of your topic
React Inline Styling with JSS

#### Topic description
Despite countless debates, inline styling is still loved by many web developers. This talk will focus on a specific library (JSS) that is my favorite among the current offerings. It will demonstrate how I ended up using the library by demonstrating the problems I had with other CSS solutions and how I solved them with JSS.

#### Presenter(s)
[Lin Han](https://github.com/hanlindev)

#### Presenter's bio
Lin is a web development professional at day and hobbyist at night. He doesn't have many commitments so he has tried many different types of stacks over the years. Now he is deeply in the camp of the React + GraphQL ecosystem. 

#### Duration
15 min

**Comment by MadeByMike** [comment]
**Title of your topic**
Understanding CSS Custom Properties

Topic **description**
Custom Properties are still a relatively new feature of CSS. Let me introduce you to the basics, some of the tricks and then show you how to use custom properties in CSS for maintainable large scale applications. Let's dive into some of the challenges of responsive design, global and local scope and theming. If there's time, let's write some code together and explore some of what you can do with custom properties.

**Presenter**
Mike Riethmuller

Presenter's bio
Hi everyone I'm Mike. I'm a web developer from Australia. I've been working with CSS pretty much since the beginning. I've got a deep appreciation for CSS and lot of experience making it work in large scale applications. I hope to share some of this with you and specifically how you can use custom properties to better manage CSS. 

**Duration**
20min, 30min, 40min -  You pick :)

**Comment by ongmin** [comment]
Thanks everyone for such an awesome edition!  🎉

Videos can be found:
1. Hands-on Performance Debugging with the browser DevTools (by @AlexLakatos )
https://engineers.sg/video/hands-on-performance-debugging-with-the-browser-devtools-talk-js-talk-css-jsconf-asia-special--3411

2. React Inline Styling with JSS (by @hanlindev)
https://engineers.sg/video/react-inline-styling-with-jss-talk-js-talk-css-jsconf-asia-special--3412

3. State of Crypto in Node.js (by @ryzokuken)
https://engineers.sg/video/state-of-crypto-in-node-js-talk-js-talk-css-jsconf-asia-special--3413

4. Understanding CSS Custom Properties (by @MadeByMike)
https://engineers.sg/video/understanding-css-custom-properties-talk-js-talk-css-jsconf-asia-special--3414

Thanks again for attending and sharing!
