### ISSUE TITLE
🎙 talk.js - September 2019

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#26]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/264555288/)
- [x] Date: 11 Sep (Wed)
- [x] Hosts: @ongmin
- [x] Venue: Cloudflare, 182 Cecil Street, Level #35-01, Singapore 069547

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by EdgeJay** [comment]
**Title of your topic**
Web Components In Practice

**Topic description**
In Feb 2019 edition of Talk.js, Aelbore gave an intro to Web Components, now I would like to deep-dive into implementing common features found in most web apps:

- CSS styling
- State management
- Pre/Server-side rendering
(this list could change as I build the deck)

In my presentation I will also attempt to implement the discussed features using browser API without third-party library help, and then compare with projects that use web components based third-party libraries.

**Presenter(s)**
Huijie (@EdgeJay)

**Presenter's bio**
Engineering Manager for Web @ [HOOQ](https://www.hooq.tv), likes to tinker with web-related stuff during his free time.

**Duration**
25 minutes for presentation; 5 mins for Q&A, discussion

**Deck URL (if any)**
Will add this part later

**Comment by anontyro** [comment]
**Title of your topic**
Svelte: streamlined, lightweight web apps

**Topic description**

Vue React and Angular have been around for sometime now and follow rather similar paradigms Svelte really shakes up how we compose and create awesome apps by pulling Javascript into a compiler to generate lean awesome apps.
 - What is Svelte
 - How does it differ from the competition
 - Svelte compiler
 - Why would I use it
 - Some Code

**Presenter(s)**
Alex (https://github.com/anontyro) Frontend developer at HOOQ

**Presenter's bio**
Frontend developer who is always looking to tinker and try new things regardless of area. Exploring new and exciting developments in Svelte, Rust and others...

**Duration**
25 minutes with 5 minutes Q&A

**Comment by KeelinChan** [comment]
**Title of your topic**
Seeking the right Page

**Topic description**
Most developers use limit and offset to page through a large result set from a SQL database. 

However, as the size of the result set grows, it will take longer and longer to retrieve each page because the query needs to iterate through all the previous records before it returns the current offset. In this case, indexes don't help.

To increase performance, we will explore implementing the seek method using nodejs and Sequelize. 

**Presenter(s)**
Steven Chan (https://github.com/KeelinChan) all my code is on bitbucket though

**Presenter's bio**
System designer, architect and backend developer. Currently interested in privacy and cryptography.

**Duration**
15 minutes for the presentation and 5 minutes Q&A.

**Deck URL (if any)**
TBD

**Comment by eriknguyen** [comment]
__Title of your topic__
Crafting your dev experience in a component age


__Topic description__
UI componentization is not a new idea. All modern and complex front-ends are composed by multiple UI components. While having your own reusable components library is extremely useful, especially to improve consistency and efficiency when you are working on multiple projects across teams, maintaining it is not a trivial task considering all the aspects involved: implementing, testing, reviewing, designer feedback, versioning, publishing, iterating that process over and over; not to mention, the typical challenges that arise: legacy code, CSS architecture, and data modelling. In this discussion, we’ll explore how to improve our own development experience by managing components library in a monorepo with Lerna in addition to leveraging latest version of Storybook and Jest. Besides the main component development, this talk will also demonstrate how to start coding much faster by writing just a very simple generator tool and how to publish all your components using both NPM and Github.


__Presenter(s)__
Erik Nguyen

__Presenter's bio__
Front End Engineer @ [Rakuten Viki](https://www.viki.com/). Obsessed about development productivity, passionate about the React ecosystem and how to utilize it to improve web quality and development experience across projects.


__Duration__
25 minutes for presentation; 5 mins for Q&A, discussion

__Deck URL (if any)__
*TBC*

**Comment by JeremySmoler** [comment]
**Title of your topic**
Graphics in JavaScript, for Business and Leisure

**Topic description**
A review of modern JavaScript graphics rendering options, including SVG, canvas, and WebGL, with exploration their application to business charts and video games.

**Presenter(s)**
Jeremy Smoler

**Presenter's bio**
Enterprise Engineer at Facebook Singapore, former software developer for Oracle USA, occasional game developer

**Duration**
20 min to present + 5 min for Q&A

**Comment by ongmin** [comment]
Hi @EdgeJay @anontyro @KeelinChan @eriknguyen @JeremySmoler! 👋

Sorry for such a slow summary on my part and thank you so much for proposing your talks, they all sound really great! I've just updated the venue too, this month's meetup will be at Cloudflare.

Unfortunately time is limited and if its alright, could we either i) move 2 talks to next month instead or ii) move one and cut time on the other talks so we fit in 4? 

Q1. @EdgeJay are you still on for this month?
Q2. @anontyro @KeelinChan @eriknguyen would anyone be open to October's spots?
Q3. Can everyone cut their required talk + Q&A time to 20 minutes?

I know @JeremySmoler has to do it this month due to travel, he posted last but we started discussing early in July (before @KeelinChan's post to be precise). 

Let me know what you each think so we can sort it out. 
Thanks a ton everyone. 🙇‍♀️

**Comment by ongmin** [comment]
Meetup link: https://www.meetup.com/Singapore-JS/events/264555288/

**Comment by anontyro** [comment]
Hi @ongmin I can move to next month that is also fine also I'll aim to shorten as well to be just a 20min thing :)

**Comment by KeelinChan** [comment]
Yes I can cut the talk and Q&A time to 20 minutes

Steven Chan
Mobile: +65 9796 5693
http://sg.linkedin.com/in/keelinstevenchan

**Comment by eriknguyen** [comment]
Yes I'm good with October slot

**Comment by JeremySmoler** [comment]
>
> Q3. Can everyone cut their required talk + Q&A time to 20 minutes?
>

Sure, can do.

Jeremy

**Comment by EdgeJay** [comment]
Hi @ongmin I will move my talk to Oct too.

**Comment by eriknguyen** [comment]
> **Title of your topic**
> Crafting your dev experience in a component age
> 
> **Topic description**
> UI componentization is not a new idea. All modern and complex front-ends are composed by multiple UI components. While having your own reusable components library is extremely useful, maintaining it is not a trivial task considering all the aspects involved: implementing, testing, reviewing, designer feedback, versioning, publishing, iterating that process over and over. In this discussion, we’ll explore how to improve our own development experience by managing components library in a monorepo with Lerna in addition to leveraging latest version of Storybook and Jest. Besides that, we will also demonstrate how to start coding much faster by writing a code generator and how to publish our components using NPM and Github.
> 
> **Presenter(s)**
> Erik Nguyen
> 
> **Presenter's bio**
> Front End Engineer @ [Rakuten Viki](https://www.viki.com/). Passionate about the React ecosystem and how to utilize it to improve web quality and development experience.
> 
> **Duration**
> 25 minutes for presentation; 5 mins for Q&A, discussion
> 
> **Deck URL (if any)**
> _TBC_

Moved my talk to Oct too.

**Comment by ongmin** [comment]
Thanks everyone! So seems like we now have 3 talks for September and no need to shorten our talks by much. :)

1. Svelte: streamlined, lightweight web apps (by @anontyro) - 20mins + 5mins Q&A
2. Seeking the right Page (by @KeelinChan) - 15 mins + 5mins Q&A
3. Graphics in JavaScript, for Business and Leisure (by @JeremySmoler) - 20mins + 5mins Q&A

I'll go ahead and update the meetup page with the above. See you all next Wednesday! :)

**Comment by ongmin** [comment]
Videos here:

1. [Svelte: streamlined, lightweight web apps by Alex Wilkinson](https://engineers.sg/video/svelte-streamlined-lightweight-web-apps-talk-js--3648)
2. [Seeking the right Page by Steven Chan](https://engineers.sg/video/seeking-the-right-page-talk-js--3647)
3. [Graphics in JavaScript, for Business and Leisure by Jeremy Smoler](https://engineers.sg/video/graphics-in-javascript-for-business-and-leisure-talk-js--3653)

**Comment by ongmin** [comment]
Hi Alexander and Jeremy! (@anontyro @JeremySmoler)
If you would like to add your deck and repo, please feel free to add it here. Would be great for people to be able to to find them again. :)
