### ISSUE TITLE
🎙 chat.js - October 2019

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#28]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/)
- [x] Date: 09 Oct (Wed)
- [x] Hosts: @ongmin @joeytwiddle
- [x] Venue: SP Digital

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by ongmin** [comment]
Would be cool to have some open floor in depth discussions for October, any topic suggestions that might suit the Chat.js format? :)

**Comment by EdgeJay** [comment]
**Title of your topic**
Web Components In Practice

**Topic description**
In Feb 2019 edition of Talk.js, Aelbore gave an intro to Web Components, now I would like to deep-dive into implementing common features found in most web apps:

- CSS styling
- State management
- Pre/Server-side rendering
(this list could change as I build the deck)

In my presentation I will also attempt to implement the discussed features using browser API without third-party library help, and then compare with projects that use web components based third-party libraries.

**Presenter(s)**
Huijie (@EdgeJay)

**Presenter's bio**
Engineering Manager for Web @ [HOOQ](https://www.hooq.tv), likes to tinker with web-related stuff during his free time.

**Duration**
25 minutes for presentation; 5 mins for Q&A, discussion

**Deck URL (if any)**
Will add this part later

**Comment by eriknguyen** [comment]
__Title of your topic__
Crafting your dev experience in a component age


__Topic description__
UI componentization is not a new idea. All modern and complex front-ends are composed by multiple UI components. While having your own reusable components library is extremely useful, maintaining it is not a trivial task considering all the aspects involved: implementing, testing, reviewing, designer feedback, versioning, publishing, iterating that process over and over. In this discussion, we’ll explore how to improve our own development experience by managing components library in a monorepo with Lerna in addition to leveraging latest version of Storybook and Jest. Besides that, we will also demonstrate how to start coding much faster by writing a code generator and how to publish our components using NPM and Github.


__Presenter(s)__
Erik Nguyen

__Presenter's bio__
Front End Engineer @ [Rakuten Viki](https://www.viki.com/). Passionate about the React ecosystem and how to utilize it to improve web quality and development experience.


__Duration__
25 minutes for presentation; 5 mins for Q&A, discussion

__Deck URL (if any)__
*TBC*

**Comment by LoneRifle** [comment]
#### Title of your topic
Using the Strangler Pattern to move from AngularJS to React/Vue 

#### Topic description
This presentation describes migrating a legacy AngularJS frontend incrementally, using the Strangler Pattern to provide the means to rewrite the frontend on a component-by-component basis. This presentation will be helpful to those who are looking to migrate sizable AngularJS codebases while mitigating the inherent risks of doing so

#### Presenter(s)
Alwyn Tan (@LoneRifle)

#### Presenter's bio
Alwyn currently works for [Open Government Products](https://open.gov.sg), which builds technology for the public good. Whilst there, he has worked on [Beeline](https://app.beeline.sg), [FormSG](https://form.gov.sg) and [OpenDoc](https://github.com/opendocsg). A recovering Java addict, Alwyn previously worked in the finance sector, building systems for trading desks.

He is more comfortable writing backend code than frontend code, and so may not be able to answer all your questions concerning this presentation.

#### Duration
20 minutes for presentation; discussion

#### Deck URL (if any)
TBA

#### References
https://github.com/LoneRifle/react-mounting-angularjs-router-animate ([vue](https://github.com/LoneRifle/react-mounting-angularjs-router-animate/tree/vue))
https://github.com/LoneRifle/react-mounting-angularjs ([vue](https://github.com/LoneRifle/react-mounting-angularjs/tree/vue))
https://softeng.oicr.on.ca/chang_wang/2017/04/17/Using-AngularJS-components-directives-in-React/

**Comment by deepakshrma** [comment]
@ongmin Is this still open to adding topics?

**Comment by LoneRifle** [comment]
Hello @ongmin - what's the plan in terms of venue, etc? Can @opengovsg step in to help?

**Comment by ongmin** [comment]
@deepakshrma hi! Unfortunately three talks for the chat format will be full enough. What’s your topic and how long is the talk? Would November work for you? :) 

@lonerifle Hi Alwyn, was trying to line up venue with @opengovsg but that fell through, hopefully for November? :)

**Comment by LoneRifle** [comment]
Sure, I'll leave you to work it out with my colleagues

**Comment by deepakshrma** [comment]
@ongmin Added already,  Please check.
