### ISSUE TITLE
🎙 talk.js - October 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/talk.js#3]
### 📝 Details
- [x] Event: [talk.js]()
- [x] Date: 25 October 2017 (Wednesday)
- [x] Hosts: @jsstrn
- [x] Venue: PayPal Singapore, Suntec Tower 5

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks
- [x] **TDD in React** by Chua Yew Wee @weewey 
- [x] **Supercharging your maps with React** by Divya Sasidharan @shortdiv 

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [ ] Check available dates on [We Build SG](https://webuild.sg/)
- [ ] Confirm date and venue availability with @realsoelynn
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by conanak99** [comment]
**Title of your talk**
The evolution of JS Asynchronous Call

**Talk description**
How we do asynchronous call in JS "the right way"
From callback and callback hell to ES6 promise, generator and ES7 async/await

**Presenter(s)**
Pham Huy Hoang - [https://github.com/conanak99](https://github.com/conanak99)

**Presenter's bio**
Senior Front-End Software Engineer at [Algomerchant Singapore](https://www.algomerchant.com/)
I'm interested in JS technology in both front-end and back-end. My favorite technologies are Webpack, React + Redux, ReactNative.

**Duration requested**
30min

**Deck URL**
In progress - Will be updated later

**Comment by jsstrn** [comment]
@conanak99 thank you for submitting your talk.. if you're available to speak on 20 September, please consider speaking in next month's talk.js - See issue #2 for details

If, however, you're only available in October, I'll add your talk here instead. Let me know. Thank you.

**Comment by conanak99** [comment]
Hi @jsstrn , I have rearranged my schedule so I can speak in September's talk.js. Please move my entry to September then.
I'm working on the speaking deck, should be finished this weekend or next weekend 😄

**Comment by jsstrn** [comment]
@conanak99 your talk has been moved to September. Thank you!

**Comment by weewey** [comment]
## TDD in React

Demonstrating the workflow of writing tests of **React Components using Enzyme & Jest**
* shallow rendering
* snapshots
* assertions

Presenter(s)

https://github.com/weewey

Presenter's bio

A developer currently in **Accenture Digital Analytics.**
Loving the JS fatigue and all things new (AI / machine learning)

Duration requested
30mins

**Comment by jsstrn** [comment]
Hi @weewey, thanks for your talk proposal. See you in October.

**Comment by sudheerj** [comment]
Boostup Angular UI development in JHipster using JHipster-PrimeNG module.

State of JHipster and Angular
Quick start of application development using top trending JHipster-PrimeNG module
Future proposals on React and Vue

Presenter(s)

https://github.com/sudheerj

Presenter's bio

Author,Speaker and Tech enthusiast
http://sudheerjonna.com/
https://twitter.com/?lang=en

Duration requested
20-30mins

**Comment by shortdiv** [comment]
## Supercharging your Maps with React. 😎 🗺️
Maps are an integral feature in many modern applications. They are frequently used to optimize travel routes and delivery systems, and to visualize geographic-related data such as weather and traffic that power applications we love and rely on in our daily lives. Historically, the process of making an interactive map for the web has been a messy process. Handling the state of the map, such as zoom level, showing and filtering selected markers, and other complex interactions, require a tangle of event listeners and handlers to ensure the map responds appropriately to a user’s actions. In this talk, we will explore the process of leveraging React and it's component lifecycle to make cool interactive maps without all the fuss. 

### Presenter(s)
[Divya Sasidharan](twitter.com/shortdiv)

### Presenter Bio
Software Engineer at [Lucro Global LLC](http://getlucro.com/)
I'm excited by all things open source and—most recently—maps. 

### Duration 
20 mins

**Comment by jsstrn** [comment]
Hi @sudheerj and @shortdiv, thanks for submitting your talk proposals this month! See you at talk.js 🎉

**Comment by sudheerj** [comment]
Hi @jsstrn,

   Is it possible to change the date other than oct 25th. Because it is conflicting with my other schedules.

Regards,
Sudheer

**Comment by jsstrn** [comment]
@sudheerj unfortunately that won't be possible. Perhaps you'd like to schedule your talk for next month instead?

**Comment by sudheerj** [comment]
@jsstrn Okay. I will plan for November month. Thanks.

**Comment by jsstrn** [comment]
Thanks for speaking this month @weewey and @shortdiv!

**Comment by GIANTCRAB** [comment]
talk by @weewey https://youtu.be/OzLK_RWWCZw

talkby @shortdiv https://youtu.be/LrqmA_BoV9c

**Comment by jsstrn** [comment]
Thanks @GIANTCRAB
