### ISSUE TITLE
talk.js - November 2019

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#30]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/)
- [x] Date: 13 Nov (Wed)
- [x] Hosts: @ongmin @joeytwiddle
- [x] Venue: Ascenda, ARC380, 380 Jalan Besar, floor 12

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by sathishk** [comment]
**Title of your topic**
Confusions and Confessions of a Web Developer

**Topic description**
I would like to share my thoughts on what we go through as a web developer during this ever-changing landscape. How and why one should look beyond these new tools, techniques, frameworks, and technology to move forward.  

**Presenter**
Sathish Kumar Thiyagarajan

**Presenter's bio**
I am Sathish Kumar Thiyagarajan working as a Solution Architect. I practice Open Source technologies (both by using as well as contributing) around Java, NoSQL Databases and Web. I believe speaking about/listening to technology is the best way to learn and you can find me doing the same in meetups around Chennai and Bengaluru.

**Duration**
5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.

**Comment by deepakshrma** [comment]
## Title of your topic:

Flutter, Create a highly scalable native-like mobile app.

## Topic description
Flutter is a framework/SDK provided and maintained by Google. It is used in many apps of google including [Google Ad](https://flutter.dev/showcase). Dart is used as the language to write the code.  Dart can be also used as a server-side/backend language. 
**Agenda:**

 - Introduction to Flutter
 - Running App in Mutilple platform(ios,
   android and Web)
 - Architectural overview of the SDK and codebase.

Flutter is Google’s UI toolkit for building beautiful, natively compiled applications for [mobile](https://flutter.dev/docs), [web](https://flutter.dev/web), and [desktop](https://flutter.dev/desktop) from a single codebase.

[Resource: [https://flutter.dev/](https://flutter.dev/)]

## Presenter
[Deepak Vishwakarma](https://github.com/deepakshrma)

## Presenter's bio
UI/UX developer at @ DBS Bank. Having more than 8 years of industry experience in development. I have a tech lover, polyglot developer. Like to explore new programming languages and discuss architecture challenges.

## Duration
20 minutes for presentation; 5 mins for Q&A, discussion

**Comment by pkamath2** [comment]
Title of your topic:
Generative Art using Genetic Algorithms and Neural networks

Topic description
A talk based on creating a Generative Art system using Genetic Algorithms and Neural Networks. This idea to create abstract patterns is based out of Genetic or Evolution based Art systems like DNGA, SNGA or Picbreeder, but created in Javascript using Tensorflow.js, Node & D3.

Presenter(s)
Purnima Kamath
(@purnimakamath) https://twitter.com/purnimakamath

Presenter's bio
Purnima is a Lead Engineer at Oliver Wyman. She is also an amateur generative artist and painter in oils. She is also a Director on the Women Who Code network and an evangelist for YOW! Conference in Singapore.

Duration
20 mins presentation 5 mins Q&A if time allows.

**Comment by wlwl2** [comment]
**Title of your topic**
Programming Practices

**Topic description**
I will be going through an NPM package that I recently published (https://github.com/wlwl2/case-utils), some programming best practices (https://github.com/timoxley/best-practices), and the Atom text editor https://atom.io/. 

**Presenter**
William Lim

**Presenter's bio**
William Lim builds websites, games, mobile apps, and other applications. He has done web development in both corporate and startup working environments. Some of his applications are open-source and there are links to them on his website (wlwl2.com). Topics that he is particularly interested in at the moment include: web, game and mobile development, Chinese and Japanese translations, and fonts and typography.

**Duration**
20 mins presentation 5 mins Q&A if time allows. (I'll try to make it shorter).

**Comment by chr15m** [comment]
### Title of your topic
[Bugout](https://github.com/chr15m/bugout): practical decentralization with WebRTC.

### Topic description
[Bugout](https://github.com/chr15m/bugout) is a JavaScript library for building decentralized applications on the web. This talk demonstrates how to build your own decentralized peer-to-peer and client-server web apps using Bugout. The talk will also cover the the cryptography and architecture of the library and its relation to WebTorrent.

### Presenter
Chris McCormick

### Presenter's bio
Chris McCormick is a freelance developer from Perth, Western Australia, who has been building weird software for a couple of decades. I'm visiting Singapore this week and discovered your cool meetup! \o/

### Duration
20 minutes

**Comment by joeytwiddle** [comment]
Hi @sathishk and @pkamath2 we have you down on the schedule already.

@chr15m We would be really interested to hear your talk this evening. Are you still available? Hope to see you later!

@wlwl2 Since Chris is only visiting Singapore this week, we would like to give his talk priority. But hopefully we can hear your talk at a future meetup. But anyway, please feel free to briefly advertise your library and any other tips you have in the open mic session at the end.

**Comment by chr15m** [comment]
@joeytwiddle yes I'll be there, thank you very much. See you then! :pray:

**Comment by wlwl2** [comment]
@joeytwiddle May I just postpone my talk (maybe) for another talk.js?

**Comment by joeysino** [comment]
@wlwl2 If you like, then yes you can postpone. I will just have to wait to learn about Atom!

You can still plug your new NPM package in the open mic session. :-)

**Comment by ongmin** [comment]
Thanks for the talks and for coming around!
Here are the video recordings from the awesome engineers.sg:

1. https://engineers.sg/video/confusions-and-confessions-of-a-web-developer-singaporejs--3799
2. https://engineers.sg/video/generative-art-using-genetic-algorithms-and-neural-networks-singaporejs--3798
3. https://engineers.sg/video/bugout-practical-decentralization-with-webrtc-singaporejs--3797
