### ISSUE TITLE
talk.js - January 2020 🎉

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#31]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/)
- [x] Date: 15 Jan (Wed)
- [x] Hosts: @ongmin @joeytwiddle
- [x] Venue: Open Gov - GovTech, Funan

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by thorsten-stripe** [comment]
**Title of your topic**
🔮The Future of JavaScript

**Topic description**
Let's look at some of the new features that are coming to JavaScript in 2020 (TC39 proposals, Web APIs), the current state of Frontend Frameworks and new features coming to them, and other trends in the frontend development space. I'll be giving a brief overview of what's happening in the JS (and adjacent) ecosystems and hopefully inspire you to dig deeper into some of these topics :)

**Presenter**
[Thor](https://twitter.com/thorwebdev) (雷神)

**Presenter's bio**
Hello, I'm [Thor](https://twitter.com/thorwebdev) (雷神), a Developer Advocate at Stripe working with many different technologies on the web to grow the GDP of the internet. Having spent most of my time with Stripe users in Europe, I recently moved to Singapore to learn from and all about APAC's developer communities.

**Duration**
20min + 5min discussion

**Deck URL**
TBA

**Comment by liangyuanruo** [comment]
**Title of your topic**
Optimising Zero-knowledge Decryption Performance in FormSG

**Topic description**
Zero-knowledge, end-to-end encryption systems provide higher security at the cost of offloading computational requirements to clients. This talk discusses how the [FormSG](form.gov.sg) team scaled in-browser decryption performance to hundreds of thousands of online form submissions, which was successfully used for the [Natioanl Day 2019 Ticket Applications](https://blog.data.gov.sg/powering-national-day-parade-ticket-applications-5a6f5cb66393) and more recently, the [Bicentennial Notes applications](https://www.mas.gov.sg/currency/singapore-bicentennial-commemorative-note).

**Presenter(s)**
[Yuan Ruo](https://github.com/liangyuanruo)

**Presenter's bio**
Hello, I'm [Yuan Ruo](https://github.com/liangyuanruo), a software engineer from [Open Government Products](https://open.gov.sg) that's working on tech products for the public good. 

**Duration**
20 minutes for presenting an introduction to the topic + 5 minutes for discussion.

**Deck URL**
TBA

**Comment by swcarlosrj** [comment]
**Title of your topic**
🚀 End-to-end Type-Safe GraphQL Apps

**Topic description**
Discover all the benefits for adding End-to-end Type-Safety to your GraphQL App with this demo-based talk. You’ll want to refactor your codebase in order to take the advantages of GraphQL, TypeScript & React working together. Apollo, Auto-gen Types & Hooks would build the pillars of a SpaceX demo.

**Presenter**
[Carlos Rufo](https://twitter.com/swcarlosrj) 

**Presenter's bio**
Carlos Rufo is a passionate developer and speaker aficionado. While he codes with different B/FE techs, his go-to for every project is his crush: GraphQL. He is very active in the GraphQL ecosystem where he has collaborated with across numerous internal & external projects, such as HowToGraphQL, SpaceX GraphQL API and recently, organizing GraphQL Hong Kong.

**Duration**
20min + 5min discussion

**Deck URL**
TBA

**Comment by ongmin** [comment]
Hi @thorsten-stripe @liangyuanruo @swcarlosrj!
Thanks for the talk submissions, see you all Wednesday. :)

**Comment by swcarlosrj** [comment]
@ongmin cannot comment on meetup.com, here's my talk resources:

Thanks everyone who attended, here the slides:

🚀 End-to-end Type-Safe #GraphQL Apps

📚 Deck: https://slides.com/swcarlosrj/end-to-end-type-safe-graphql-apps-javascript-singapore#
🛠 Code: https://github.com/spacexland/api
⭐ API: https://api.spacex.land/graphql

Looking forward to seeing y'all soon 😄 (*made to my flight on time 🥳)

**Comment by ongmin** [comment]
Videos of the talks:
https://engineers.sg/video/end-to-end-type-safe-graphql-apps--3921
https://engineers.sg/video/the-future-of-javascript--3923
https://engineers.sg/video/optimising-zero-knowledge-decryption-in-formsg--3922

Thanks everyone!
