### ISSUE TITLE
talk.js - April 2020 (online)

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#34]
### 📝 Details
- [x] Event: [virtualtalk.js](https://www.meetup.com/Singapore-JS/events/270077681/)
- [x] Date: ~15~ 22 April (Wed)
- [x] Hosts: @joeytwiddle @eriknguyen 
- [x] Venue: Zoom

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Teleconference open - _Mukbang_
7.25pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.45pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- Data Visualizations and Maps with JavaScript by _William Lim_ (@wlwl2, [web](https://wlwl2.com/), [twitter](https://twitter.com/wlwlz), [LinkedIn](https://linkedin.com/in/wlwl2/))
- A look under the hood of Stripe.js by _Ankita Gupta_ (@ankita-stripe, @ankitagupta12, [twitter](https://twitter.com/gazubi))

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/events)
- [x] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by joeytwiddle** [comment]
Hi @wlwl2 @ankita-stripe, are you still happy to present to us on Wednesday?

How about you Chinmay @thchia?

**Comment by wlwl2** [comment]
@joeytwiddle Yes, that should be alright. If you still want to postpone talk.js, I'm also fine with that.

**Comment by ankita-stripe** [comment]
yeah, same! okay to do on wednesday or postpone further

**Comment by thchia** [comment]
@joeytwiddle I think I need bow out 😭 - I won’t be ready by Wednesday. I’m sorry I keep missing the updated dates, so last month and this month it’s caught me a bit by surprise and I’ve been unprepared.

**Comment by joeytwiddle** [comment]
Thanks for your replies. No problem Thomas. Let's have two presentations on Wednesday, to cheer everybody up!

**Comment by joeytwiddle** [comment]
@wlwl2 @ankita-stripe We are having some technical difficulties this week, so let's reschedule for _next week_.

We'll let you know once the day and time is confirmed.

Sorry for the miss-start. We'll try and get up to speed soon!

**Comment by wlwl2** [comment]
Ok!

**Comment by joeytwiddle** [comment]
We're all set for Wednesday evening: https://www.meetup.com/Singapore-JS/events/270077681/

Hope you're still happy to join us Ankita! @ankita-stripe

**Comment by ankita-stripe** [comment]
sounds good!

**Comment by ankita-stripe** [comment]
i'll only be able to join closer to 7:25, before the talk starts.

**Comment by ankita-stripe** [comment]
what's the meeting password?

**Comment by ankita-stripe** [comment]
@joeytwiddle let me know. i can't find it on the meetup page

**Comment by ongmin** [comment]
@ankita-stripe 633108

**Comment by eriknguyen** [comment]
For tracking, the 2 talks of today's meetup are from #32 

1. [**Data Visualizations and Maps with JavaScript** by William](https://github.com/SingaporeJS/talk.js/issues/32#issuecomment-575523790)

2. [**A look under the hood of Stripe.js** by Ankita](https://github.com/SingaporeJS/talk.js/issues/32#issuecomment-576750295)
