### ISSUE TITLE
🎙️ talk.js - July 2020 (online)

### ISSUE THREAD

**Issue by eriknguyen** [SingaporeJS/talk.js#39]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/271138941/)
- [x] Date: 15 July (Wed)
- [x] Hosts: @joeytwiddle @eriknguyen @ongmin
- [x] Venue: Zoom?

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Teleconference open - _Mukbang_
7.25pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.45pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by trungk18** [comment]
**Title of your topic**

Angular - Using Visitor design pattern with Typescript

**Topic description**

I'll be sharing my experience on applying visitor design pattern on an Angular application

**Presenter(s)**

Trung Vo ([https://github.com/trungk18](https://github.com/trungk18))

**Presenter's bio**

I am Front end Engineer at [Zyllem](https://www.zyllem.com/) in the past 4 years where I worked mostly with Angular and TypeScript.

I am also a community leader of [Angular Vietnam](https://github.com/angular-vietnam), a group for developer who is currently working with Angular in Vietnam.

**Duration**

15-20min sharing + 5min for Q&A

**Deck URL (if any)**

Work in Progress!

The blog post you can find at https://trungk18.com/experience/typescript-visitor-pattern-with-google-maps-api/

**Comment by joeytwiddle** [comment]
**Title of your topic**

Introduction to userscripts

**Topic description**

How to enjoy userscripts and write your own

**Presenter(s)**

joeytwiddle ([https://github.com/joeytwiddle](https://github.com/joeytwiddle))

**Presenter's bio**

Full-stack-overflow JavaScript developer who likes node.js, Linux, userscripts and dwitter.net

**Duration**

20min maybe a little more sharing + 5min for Q&A

**Deck URL**

https://slides.com/joeytwiddle/userscripts2020

My published userscripts: https://openuserjs.org/users/joeytwiddle/scripts

**Comment by wgao19** [comment]
Hey @joeytwiddle @ongmin has this happened yet? I'm on an RK slide and would like to refer people to here also, can share a bit details of the event please?

**Comment by eriknguyen** [comment]
> Hey @joeytwiddle @ongmin has this happened yet? I'm on an RK slide and would like to refer people to here also, can share a bit details of the event please?

Yay, thanks alot @wgao19 We have postponed this so it will be next Wednesday
