### ISSUE TITLE
🎙 talk.js - November 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/talk.js#4]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/245133765)
- [x] Date: 29 November (Wednesday)
- [x] Hosts: @jsstrn
- [x] Venue: PayPal Singapore, Suntec Tower 5

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks
- [x] **Continuously delivering full-stack JavaScript** by Joseph Matthias Goh @zephinzer 
- [x] **Using native Node.js HTTP/2 support** by Sebastiaan Deckers @sebdeckers 
- [x] **What's new in Angular v5** by Mar Anthony Go @damaranthony 

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [ ] Check available dates on [We Build SG](https://webuild.sg/)
- [ ] Confirm date and venue availability with @realsoelynn
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by jsstrn** [comment]
@realsoelynn could we book 29 November (Wednesday) for the next talk.js?

**Comment by zephinzer** [comment]
**Title of your talk**

deploying.js

**Talk description**

If an application is written but never deployed, was it ever written? JS is a product-centric language, any application that can be written in JS will eventually be, and good deployment practices is the key to releasing a maintainable product that can be iteratively improved upon. In this session, I'll be sharing on deployment techniques we have explored and are using in one of our first full stack JS products developed with Agile methodologies at Government Digital Services, GovTech.

**Presenter(s)**

Joseph Matthias Goh - @zephinzer

**Presenter's bio**

Joseph is a full stack web developer and DevOps engineer at Government Digital Services, GovTech Singapore, creating and deploying awesome citizen-centric applications. 

**Duration requested**

20min

**Deck URL (if any)**

NA yet, will update when it's in

**Comment by jsstrn** [comment]
@zephinzer I love this line, "if an application is written but never deployed, was it ever written?" - looking forward to your talk next month!

@sudheerj would you like to talk at talk.js in November? Let me know and I'll add your name to the speakers list.

**Comment by sudheerj** [comment]
@jsstrn Thanks. Please add me for next month. But I can't make it on Wednesdays because of training schedules.

**Comment by zephinzer** [comment]
@jsstrn haha thank you! Looking forward to hearing opinions from the talk.js community too(:

**Comment by sebdeckers** [comment]
**Title of your talk**

Using native Node.js HTTP/2 support on the client and server

**Talk description**

Node.js 8.4.0 shipped the new http2 module. It is now unflagged since 9.0.0 and ready for fun.

I will present:
- the internal workings of the http2 module, its design and capabilities;
- performance metrics compared with other HTTP/2.0 server implementations;
- new capabilities like Push Promises, stream priority, and the `respondWithFile` API;
- how to use it on the client via the core API or fetch() implementations;
- how to use it on the server via the core API or compatibility API with familiar frameworks (Fastify, Connect, Express, Hapi, etc).

**Presenter(s)**

Name: Sebastiaan Deckers
Twitter/GitLab/GitHub: @sebdeckers

**Presenter's bio**

Open source indie hacker, creator of [http2.live](https://http2.live) HTTP/2-born hosting service, Node.js Collaborator (part of HTTP/2 team).

**Duration requested**

Whatever fits the schedule. (10min, 20min, 30min)

**Deck URL (if any)**

Coming soon

**Comment by damaranthony** [comment]
**Title of your talk**
Roughly 8 months from v4, what's new Angularjs v5?

**Talk description**
A new version of Angularjs has been released recently. I'd like to share a couple of interesting updates that I've learned through exploring the new version of the framework. 

**Presenter(s)**
Name: Mar Anthony Go
Twitter/Github: @damaranthony

**Presenter's bio**
Web developer from the island of Mactan. 

**Duration requested**
Whichever is available 10min or 20min

**Deck URL (if any)**
To follow

**Comment by sudheerj** [comment]
@jsstrn As I mentioned last month, it is not possible to propose talk on Wednesdays to other training schedules. Can you please make it other than Wednesdays. Thanks.

**Comment by jsstrn** [comment]
talk.js has been scheduled for 29 November 2017 (Wednesday).

Don't forget to RSVP and tell all your friends about the event - https://www.meetup.com/Singapore-JS/events/245133765 

Thank you and see you in 2 weeks.
