### ISSUE TITLE
🎙️ talk.js - August 2020 (online)

### ISSUE THREAD

**Issue by joeytwiddle** [SingaporeJS/talk.js#40]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/272461140/)
- [x] Date: 26 August (Wed)
- [x] Hosts: @joeytwiddle @eriknguyen @ongmin
- [x] Venue: Zoom

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Teleconference open - _Mukbang_
7.25pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.45pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [ ] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by malgamves** [comment]
*Title of your topic*
Building a REST and GraphQL API with JavaScript in 5 minutes

*Topic description*

I'll talking about getting started with building REST and GraphQL APIs with Strapi (an open source Headless CMS) and well as querying these APIs in the frontend of your application with Nuxt.js 

*Presenter(s)*

[Daniel Madalitso Phiri](https://github.com/malgamves)

*Presenter's bio*

I'm Daniel, a retired Podcaster, Lorde super fan, Software Developer, Technical Writer and currently - Developer Advocate at Strapi.

*Duration*

20 minutes

**Comment by eriknguyen** [comment]
@malgamves Thank you for the submission. Strapi is really interesting, looking forward to it!

**Comment by malgamves** [comment]
Can't wait to present it too 🎊

**Comment by trungk18** [comment]
_Title of your topic_
Behind the 900 stars repository 😂

_Topic description_
I'll be sharing my experience on some decisions that I made for my [Jira clone application](https://jira.trungk18.com/) that got the community attention
- Why TailwindCSS
- Why Akita over ngrx

_Presenter(s)_
Trung Vo (https://github.com/trungk18)

_Presenter's bio_
Hi, I'm Trung. A young and passionate front-end engineer. I'm currently helping the Angular community by creating open sources and writing about interesting and useful topics.

_Duration_
15-20min sharing + 5min for Q&A

_Deck URL (if any)_
I am working on it.

**Comment by eriknguyen** [comment]
> Behind the 900 stars repository 😂

Awesome, thank you Trung! Love the title too :D

**Comment by eriknguyen** [comment]
## Also guys, do check out some other events in the local community

- Aug 24 (Mon) - JuniorDevSG Online Hangout: https://www.meetup.com/Junior-Developers-Singapore/events/272527062/
- Aug 21 (Fri) - React Knowledgeable: [RK#85 - Aug 21, 2020](https://github.com/Shopee/shopee-react-knowledgeable/issues/231)
- Sept 2 (Wed) - SingaporeCSS 54: https://singaporecss.github.io/

**Comment by tanhauhau** [comment]
I wonder do you guys still have time for another talk? 🤔

Title of your topic
Compile Svelte in your head

Topic description
How does Svelte work? How is Svelte different from other modern frameworks? Why compile? Don't worry, I'll explain what is Svelte, how it works, and I promise you can fit all of that into your head.

Presenter(s)
Tan Li Hau
github: @tanhauhau
twitter: https://twitter.com/lihautan

Presenter's bio
Hi, I'm Li Hau. Frontend Engineer at Shopee. I like to create bugs and fix them. Recently I am trying to write down my learnings and thought processes in my blog https://lihautan.com/. Also, I am currently a maintainer of Svelte, hopefully it meant less bug for Svelte.

Duration
20 mins + 5 mins Q&A.

Deck URL (if any)
You can add this part in later

**Comment by eriknguyen** [comment]
@tanhauhau Yes **Swelte**!!! Thanks alot for sharing about that! We definitely can squeeze in 3 talks but we thought it's better to spread it to next month. Would you mind speaking in Sep instead?

**Comment by tanhauhau** [comment]
OK. Will confirm again when the date is confirmed

**Comment by eriknguyen** [comment]
> OK. Will confirm again when the date is confirmed

Cheers! Tentatively it'll be on the 23rd of Sep
