### ISSUE TITLE
🎙️ talk.js - September 2020 (online)

### ISSUE THREAD

**Issue by eriknguyen** [SingaporeJS/talk.js#41]
### 📝 Details
- [x] Event: https://www.meetup.com/Singapore-JS/events/273131240/
- [x] Date: 23 September (Wed)
- [x] Hosts: @joeytwiddle @eriknguyen @ongmin
- [x] Venue: Zoom

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Teleconference open - _Mukbang_
7.25pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.45pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [ ] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by eriknguyen** [comment]
Talk moved from [August thread](https://github.com/SingaporeJS/talk.js/issues/40#issuecomment-674785423_). To be confirmed by @tanhauhau, thank you for submitting again :D 

**Title of your topic**
Compile Svelte in your head

**Topic description**
How does Svelte work? How is Svelte different from other modern frameworks? Why compile? Don't worry, I'll explain what is Svelte, how it works, and I promise you can fit all of that into your head.

**Presenter(s)**
Tan Li Hau
github: @tanhauhau
twitter: https://twitter.com/lihautan

**Presenter's bio**
Hi, I'm Li Hau. Frontend Engineer at Shopee. I like to create bugs and fix them. Recently I am trying to write down my learnings and thought processes in my blog https://lihautan.com/. Also, I am currently a maintainer of Svelte, hopefully it meant less bug for Svelte.

**Duration**
20 mins + 5 mins Q&A.

**Deck URL (if any)**
You can add this part in later

**Comment by eriknguyen** [comment]
> Talk moved from [August thread](https://github.com/SingaporeJS/talk.js/issues/40#issuecomment-674785423_). To be confirmed by @tanhauhau, thank you for submitting again :D
> 
> **Title of your topic**
> Compile Svelte in your head
> 
> **Topic description**
> How does Svelte work? How is Svelte different from other modern frameworks? Why compile? Don't worry, I'll explain what is Svelte, how it works, and I promise you can fit all of that into your head.
> 
> **Presenter(s)**
> Tan Li Hau
> github: @tanhauhau
> twitter: https://twitter.com/lihautan
> 
> **Presenter's bio**
> Hi, I'm Li Hau. Frontend Engineer at Shopee. I like to create bugs and fix them. Recently I am trying to write down my learnings and thought processes in my blog https://lihautan.com/. Also, I am currently a maintainer of Svelte, hopefully it meant less bug for Svelte.
> 
> **Duration**
> 20 mins + 5 mins Q&A.
> 
> **Deck URL (if any)**
> You can add this part in later

Hi @tanhauhau, may we confirm that we are able to give this talk on Sep 23rd? Thanks alot :)

**Comment by tanhauhau** [comment]
yes.

**Comment by thorwebdev** [comment]
#### Title of your topic
Building a Slack clone with authentication and realtime data syncing using [Supabase.io](https://supabase.io)

#### Topic description
Supabase is a Singapore based, Y Combinator backed startup, building the open source Firebase alternative. Supabase adds realtime and restful APIs to your Postgres database without a single line of code.

This will be a quick demo on how to get started with Supabase.io as your data and authentication backend when building Jamstack apps as well as a quick look at how you can [contribute](https://github.com/supabase/supabase/labels/hacktoberfest) to the Supabase project during [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

#### Presenter(s)
[@thorwebdev](https://twitter.com/thorwebdev)

#### Presenter's bio
I'm a Developer Advocate at Stripe working with many different technologies on the web to grow the GDP of the internet and enjoy contributing to open source projects where I can.

#### Duration
15 mins demo and 5 mins Q&A.

#### Resources
https://github.com/supabase/supabase/tree/master/examples/slack-clone#realtime-chat-example-using-supabase

**Comment by eriknguyen** [comment]
That's awesome. Thank you @tanhauhau @thorwebdev !!!

**Comment by ongmin** [comment]
Updated the zoom link on meetup! @thorwebdev @tanhauhau

**Comment by tanhauhau** [comment]
Link to the slides: https://docs.google.com/presentation/d/1BIU8v8LtpZSFTBk9Ag7teVk3GcRWY8Iyx3kGJiMENRM/edit?usp=sharing

**Comment by ongmin** [comment]
Svelte talk: https://engineers.sg/v/4120
Supabase.io talk: https://engineers.sg/v/4119
