### ISSUE TITLE
🎙️ talk.js - October 2020 (online)

### ISSUE THREAD

**Issue by daynin** [SingaporeJS/talk.js#42]
Hello! I'd like to propose a talk:

Title of your topic
Improve developer experience with Github Actions

Topic description
This talk about how we improved our developer experience in CSSSR (https://csssr.com/en) with Github Actions. What we used before to automate linting, testing, building, and deploying all our projects. How GH Actions make it easier to build development workflows and what you can automate with them (almost everything).

Presenter(s)
Sergey Golovin
github: @daynin
twitter: https://twitter.com/_sgolovin

Presenter's bio
Hi, I'm Sergey Golovin. Software Engineer at CSSSR. I'm a big fan of open source, contributor in some projects, podcaster and co-organizer of a developers community

Duration
30 mins + 5 mins Q&A.

**Comment by nemwiz** [comment]
**Title of your topic**

Web assembly for enterprise devs

**Topic description**

We've all heard about WebAssembly, but most of the times it's mentioned in the context of building video games, image and video compression, VR/AR etc.
However, a lot of us do not work as game developers and we don't encounter these problems in our day to day work. This brings out the question - should I even learn WebAssembly?
In this talk, I want to show some use cases in building business/enterprise applications where WebAssembly can be applied. The talk is practical and we will see how WebAssembly can improve your apps performance by order of magnitude and hopefully convince you why WebAssembly is here to stay.

**Presenter(s)**

Nemanja Ninkovic 
@nemwiz

**Presenter's bio**

Hi, my name is Nemanja Ninkovic and I'm a software engineer at Zuhlke. Passionate about problem solving and trying to keep up with the latest on the web. 

**Duration**

30 minutes

**Comment by eriknguyen** [comment]
### 📝 Details
- [x] Event: https://www.meetup.com/Singapore-JS/events/273131240/
- [x] Date: 21 October (Wed)
- [x] Hosts: @joeytwiddle @eriknguyen @ongmin
- [x] Venue: Zoom

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Teleconference open - _Mukbang_
7.25pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.45pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [ ] Check available dates on [EngineersSG](https://engineers.sg/)
- [ ] Confirm date and venue availability
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by eriknguyen** [comment]
Thanks alot @daynin and @nemwiz for proposing the talk! The meetup will happen tentatively on Oct 21st, let me know if you two are available on the date :)

**Comment by nemwiz** [comment]
@eriknguyen Yes, 21st of October sounds good. 👍

**Comment by daynin** [comment]
@eriknguyen completely available!

**Comment by eriknguyen** [comment]
@nemwiz @daynin That's awesome! Thanks alot 💯

**Comment by ongmin** [comment]
@nemwiz @daynin zoom link has been posted on meet-up :)

**Comment by daynin** [comment]
@eriknguyen hello! Looks like the event link here (https://github.com/SingaporeJS/talk.js/issues/42#issuecomment-691957048) leads to the previous event. Will it be updated later?

**Comment by eriknguyen** [comment]
> @eriknguyen hello! Looks like the event link here ([#42 (comment)](https://github.com/SingaporeJS/talk.js/issues/42#issuecomment-691957048)) leads to the previous event. Will it be updated later?

Thanks for checking in! Yes it will be published shortly :) Have a good weekend!

**Comment by nemwiz** [comment]
@eriknguyen Thanks for posting the event. In the event description there is one paragraph about Supabase, I think it was incorrectly copied over from the previous description. Can you please correct this? :) Thanks

**Comment by eriknguyen** [comment]
@nemwiz So sorry for that! And thanks alot for letting us know about it. I have corrected that part on meetup page. Looking forward to your talk on Wed!

**Comment by miccheng** [comment]
Video of @daynin's video: https://engineers.sg/v/4160

**Comment by miccheng** [comment]
Video of @nemwiz's video: https://engineers.sg/v/4159

**Comment by nemwiz** [comment]
@miccheng Many thanks for the videos Michael.
