### ISSUE TITLE
talk.js - January 2021 (online)

### ISSUE THREAD

**Issue by joeytwiddle** [SingaporeJS/talk.js#48]
### 📝 Details
- [x] Event: https://www.meetup.com/Singapore-JS/events/275699538/
- [x] Date: 20 January (third Wednesday of the month)
- [x] Hosts: @joeytwiddle @eriknguyen @ongmin
- [x] Venue: Zoom

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Teleconference open - _Mukbang_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.45pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [x] Tetris game built with Angular 10 and Akita, by Trung Vo
- [x] Introduction to Svelte actions, by Li Hau Tan

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/events)
- [x] Confirm date and venue availability
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by trungk18** [comment]
Hey guys, Merry Christmas 🎄 I would like to register for Jan 2021 talk as below. Thank you!

*Title of your topic*
A childhood memory Tetris game built with Angular 10 and Akita.

*Topic description*
I'll shared the development challenge while building Angular Tetris - [https://tetris.trungk18.com/](https://tetris.trungk18.com/) 

- Draw a tetris board and the tetrominos
- Animation/Timer
- Keyboard
- Sounds

*Presenter(s)*
Trung Vo ([https://github.com/trungk18](https://github.com/trungk18))

*Presenter's bio*

Trung is a front-end engineer who creates beautiful, performant web applications with delightful user experiences. Trung's currently with @cakedefi. He has four years of working continuously with Angular and is a community leader @Angular Vietnam, a group with more than 13k members. He writes, codes, and talks about Angular. Curious. Not a coffee drinker.

*Duration*
25-30min sharing + 5min for Q&A

*Deck URL (if any)*
Work in progress
[https://slides.com/tuantrungvo/build-a-tetris-game-with-angular-and-akita](https://slides.com/tuantrungvo/build-a-tetris-game-with-angular-and-akita)

**Comment by joeytwiddle** [comment]
Hi @trungk18 we are planning to hold the meetup next week. Is it ok for you?

**Comment by trungk18** [comment]
Hi @joeytwiddle, I am good with Wednesday next week. See you all!

**Comment by tanhauhau** [comment]
**Title of your topic**
Introduction to Svelte actions

**Topic description**
I want to make an introductory talk to [Svelte actions](https://svelte.dev/tutorial/actions).
I understand that not everyone has tried Svelte, not everyone knows about Svelte.
Instead of giving a high-level overview of everything Svelte, I am going to share 1 Svelte feature, and hope that gives everyone a glimpse of Svelte.

**Presenter(s)**
@tanhauhau (github)
[@lihautan](https://twitter.com/lihautan) (twitter)

**Presenter's bio**
Hi, I'm Li Hau. Frontend Engineer at Shopee. I like to create bugs and fix them. Recently I am trying to make [YouTube video tutorials](https://www.youtube.com/channel/UCbmC3HP3FaAFdcZkui8YoMQ). Also, I am currently a maintainer of Svelte, hopefully it meant less bug for Svelte.

**Duration**
20 minutes

**Deck URL (if any)**
TODO:

**Comment by joeytwiddle** [comment]
Thanks Li Hau! I will add yours as the second talk for this month.

**Comment by ClarisseNg** [comment]
**Title of your topic**
Introduction to Low-Code with NodeRED

**Topic description**
Developers no longer have the monopoly on making computers do their bidding. The rise of low-code solutions and visual builder tools is empowering a whole generation of new developers to bring their ideas to life with only a little coding knowledge.
Far from putting us out of a job, these tools could be useful to us as well! In this session, I will introduce you to NodeRED, a JavaScript-based open-source low-code tool. We’ll look at the basics of getting started, the tasks NodeRED is really good at, and how you can extend the NodeRED platform. 
Come along and decide if a low-code tool deserves a space in your high-code toolbox!

**Presenter(s)**
GitHub: juliacodez
Twitter: @iza_biro

**Presenter's bio**
Julia is a Developer Advocate for Vonage focusing on low-code technologies and integrations. Maker and breaker of things, explorer of yet another builder tool. Forever challenging the barriers to entry of tech, she is passionate about learning and teaching, creating resources for the community.

**Duration**
Anywhere between 25-45mins

**Deck URL (if any)**
You can add this part in later
