### ISSUE TITLE
talk.js - February 2021 (online)

### ISSUE THREAD

**Issue by joeytwiddle** [SingaporeJS/talk.js#49]
### 📝 Details
- [x] Event: https://www.meetup.com/Singapore-JS/events/276377042
- [x] Date: 17 February (third Wednesday of the month)
- [x] Hosts: @joeytwiddle @eriknguyen @ongmin
- [x] Venue: Zoom

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Teleconference open - _Mukbang_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.45pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [x] Introduction to Low-Code with NodeRED by _Julia Biro_ (@iza_biro)

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/events)
- [x] Confirm date and venue availability
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [x] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by ClarisseNg** [comment]
**Title of your topic**
Introduction to Low-Code with NodeRED

**Topic description**
Developers no longer have the monopoly on making computers do their bidding. The rise of low-code solutions and visual builder tools is empowering a whole generation of new developers to bring their ideas to life with only a little coding knowledge.
Far from putting us out of a job, these tools could be useful to us as well! In this session, I will introduce you to NodeRED, a JavaScript-based open-source low-code tool. We’ll look at the basics of getting started, the tasks NodeRED is really good at, and how you can extend the NodeRED platform.
Come along and decide if a low-code tool deserves a space in your high-code toolbox!

**Presenter(s)**
Julia Biro 
GitHub: juliacodez
Twitter: @iza_biro

**Presenter's bio**
Julia is a Developer Advocate for Vonage focusing on low-code technologies and integrations. Maker and breaker of things, explorer of yet another builder tool. Forever challenging the barriers to entry of tech, she is passionate about learning and teaching, creating resources for the community.

**Duration**
Anywhere between 25-45mins

**Deck URL (if any)**
You can add this part in later

**Comment by ClarisseNg** [comment]
> **Title of your topic**
> Introduction to Low-Code with NodeRED
> 
> **Topic description**
> Developers no longer have the monopoly on making computers do their bidding. The rise of low-code solutions and visual builder tools is empowering a whole generation of new developers to bring their ideas to life with only a little coding knowledge.
> Far from putting us out of a job, these tools could be useful to us as well! In this session, I will introduce you to NodeRED, a JavaScript-based open-source low-code tool. We’ll look at the basics of getting started, the tasks NodeRED is really good at, and how you can extend the NodeRED platform.
> Come along and decide if a low-code tool deserves a space in your high-code toolbox!
> 
> **Presenter(s)**
> Julia Biro
> GitHub: juliacodez
> Twitter: @iza_biro
> 
> **Presenter's bio**
> Julia is a Developer Advocate for Vonage focusing on low-code technologies and integrations. Maker and breaker of things, explorer of yet another builder tool. Forever challenging the barriers to entry of tech, she is passionate about learning and teaching, creating resources for the community.
> 
> **Duration**
> Anywhere between 25-45mins
> 
> **Deck URL (if any)**
> You can add this part in later

Hi Organisers, may we confirm that we are able to give this talk on 17th of Feb? Thanks alot! :)

**Comment by joeytwiddle** [comment]
Thanks @ClarisseNg. We are excited to have your talk on the 17th!
