### ISSUE TITLE
talk.js - November 2022 (in person)

### ISSUE THREAD

**Issue by joeytwiddle** [SingaporeJS/talk.js#51]
Meetup Event: [talk.js](https://www.meetup.com/singapore-js/events/289684404/)
Date: Wednesday 16th November (third Wednesday of the month)
Hosts: @joeytwiddle, Marco Podien
Location: WeWork, UE Square, [83 Clemenceau Ave](https://www.google.com/maps/search/?api=1&query=1.292933%2C%20103.84296)

With thanks to Marco Podien for arranging the hosting.

(We might combine with [Vue JS](https://www.meetup.com/Vue-JS-Singapore/) for a future event.)

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

**Comment by joeytwiddle** [comment]
**Title:** Privacy-preserving Applications – Batteries Included

**Presenter:** Marco Podien

**Abstract:**

Do you want to own your data? Do you believe you alone must decide who accesses your data and when? So do we! We want to talk about privacy-preserving applications. What that means and some of the ways we can achieve that. How you can leverage W3C standards and your JS skills to create products that put data back in the hands of its rightful owner.

We are here to change data ownership for good! Have a look at what we can offer to flatten the learning curve for these technologies and tell us what else we can do to support a developer’s journey into the undiscovered country.

Mini-Bio: Marco is the Developer Evangelist at Affinidi and an enthusiast for decentralized technologies. As an ambassador of clean code and architecture, but too lazy to remember the details, he is all-in for dev tooling. Let's find out!

**Comment by notthetup** [comment]
November or December?

**Comment by thuchede** [comment]
**Title of your topic**
The Lord of the Monorepos: An efficient setup with PNPM and NX

**Topic description**
As people shift from monolith to micro-services and micro-frontends, we are starting to see more and more teams shifting to a monorepos model. As our codebase grows and people starts collaborating heavily, we need to keep thing running efficiently. What makes a good setup for a monorepo?

**Presenter(s)**
Thomas Huchedé
https://github.com/thuchede on github
@thuchede on twitter

Presenter's bio
Thomas is a software consultant at Zenika. Developer for more than 7 years, he chose to specialise in front-end development to improve the state of current web applications in terms of performance and accessibility. 

Duration
25 min should fit.

Deck URL (if any)
Might have to update the slides but the original can be found here:
https://github.com/thuchede/pnpm-nx-demo/blob/main/slides/the_lord_of_the_monorepo.pdf
