### ISSUE TITLE
How about kick start an meetup or online event after the long pandemic? I am interested to provide a session talk about my recent learning on my project

### ISSUE THREAD

**Issue by kokkoon** [SingaporeJS/talk.js#52]

**Comment by joeytwiddle** [comment]
Hi @kokkoon, sorry for the late reply.

As you can see, we have been in downtime for a while. But when we start up again, we would be interested to hear your talk!

Hopefully we will find a second speaker, and have another meetup in the coming months.

If you are still interested to present, perhaps you could provide some details in this issue: #51

**Comment by joeytwiddle** [comment]
Hi @kokkoon, would you be interested in sharing your talk later this month?

**Comment by joeytwiddle** [comment]
Hi @kokkoon, we have another meetup booked for September. #55
