### ISSUE TITLE
talk.js - February 2023 (in person)

### ISSUE THREAD

**Issue by joeytwiddle** [SingaporeJS/talk.js#53]
Meetup Event: https://www.meetup.com/singapore-js/events/291718124/
Date: Wed 22 (last Wed of the month)
Hosts: Chinmay Pendharkar (@notthetup) and Erik Nguyen (@eriknguyen)
Location: Hackerspace

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

**Comment by linusnorton** [comment]
**Title:** Measuring team performance

**Description:** Everyone knows a high performing team when they see one, but how do you objectively measure them? What metrics are important and how do you collect them? 

**Presenter:** [Linus Norton](https://www.github.com/linusnorton/) 

**Bio:** Linus is a long time engineer and advocate for clean code, minimalism and pragmatism. He is currently a Tech Lead at the Ministry of Justice in the UK and in the process of trying to herd hundreds of developers.

**Comment by andrewbeng89** [comment]
**Title of your topic**
Learning by experimenting: Vue 3 Reactivity to build Web Components

**Topic description**
With JS framework/library fatigue at its peak, creating yet-another-JS-library is hardly something the everyday developer would want to check off their TODO list. But what if there's something to be gained in this by diving into the APIs of fundamental web technologies and popular frameworks?

(adapted and updated from an online talk presented at the [Hamburg VueJS meetup # 13](https://www.meetup.com/hamburg-vue-js-meetup/events/278870728/))

**Presenter(s)**
[Andrew Beng](https://github.com/andrewbeng89)

**Presenter's bio**
Software engineer currently focusing on frontend development for solutions in the news and media space for [Factorial](https://www.factorial.io/en/about-us), a digital agency based in Hamburg, Germany.

**Duration**
~20 minutes

**Deck URL (if any)**
[Previous edition](https://slides.com/andrewbeng89/vue-reactivity-custom-elements) - new version to follow

**Comment by joeytwiddle** [comment]
Thanks @linusnorton and @andrewbeng89 for your submissions! We are going to start looking for a venue for Wed 14th December.

**Comment by linusnorton** [comment]
Hey @joeytwiddle do you have a location?

**Comment by joeytwiddle** [comment]
@linusnorton Still working on it!

**Comment by andrewbeng89** [comment]
> @linusnorton Still working on it!

Is there a possibility to shift it to 21 Dec? (I'm also recovering from food poisoning now)

**Comment by joeytwiddle** [comment]
21st isn't really good for me either.

Sorry guys, I think we should cancel tomorrow's meetup. Let's plan for January instead.

Will you both be available for Wednesday 18th January?

**Comment by andrewbeng89** [comment]
No worries @joeytwiddle I'll book 18 Jan '23 in my calendar.

**Comment by joeytwiddle** [comment]
Hope you are feeling better @andrewbeng89 

@linusnorton Will you be available on 18th Jan? If so, I'll put you both up for the Jan meetup.

**Comment by linusnorton** [comment]
Unfortunately not but I'll put my name down next time I'm in the country

**Comment by andrewbeng89** [comment]
@joeytwiddle just following up wether the Jan 18 talk is on as planned?

**Comment by joeytwiddle** [comment]
Sorry @andrewbeng89 we announced it was cancelled on Telegram, but forgot to feedback here.

Would you be interested in presenting on Web 22 Feb?

We have confirmed a second speaker this time (Thomas Gorissen)

**Comment by notthetup** [comment]
@tpiros 👆🏾

**Comment by andrewbeng89** [comment]
> Sorry @andrewbeng89 we announced it was cancelled on Telegram, but forgot to feedback here.
> 
> Would you be interested in presenting on Web 22 Feb?
> 
> We have confirmed a second speaker this time (Thomas Gorissen)

@joeytwiddle sorry for the late reply. Unfortunately I won't be in Singapore on 22 Feb as I'll be clearing some carried over vacation days from last year.

Could you point me in the right direction to the Telegram group you mentioned?

**Comment by eriknguyen** [comment]
Hi @andrewbeng89 , here you go: https://t.me/chatjs

There's also an open channel for announcement here: https://t.me/singaporejs

Hope to have you next month maybe 🙌

**Comment by tpiros** [comment]
I can be available for a talk in March, if that's helpful at all :)

**Comment by eriknguyen** [comment]
@tpiros 🙌 That would be great! Do you mind giving us an overview of your talk in a comment here: https://github.com/SingaporeJS/talk.js/issues/54

**Comment by tpiros** [comment]
done @eriknguyen 👏
