### ISSUE TITLE
talk.js - 2023 March

### ISSUE THREAD

**Issue by eriknguyen** [SingaporeJS/talk.js#54]
Meetup Event: TBA
Date: Wed, March 22 (tentatively)
Hosts: TBC
Location: TBC

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details open>
<summary>
Click for details

</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

**Comment by andrewbeng89** [comment]
(copying over from #53)

Title of your topic
Learning by experimenting: Vue 3 Reactivity to build Web Components

Topic description
With JS framework/library fatigue at its peak, creating yet-another-JS-library is hardly something the everyday developer would want to check off their TODO list. But what if there's something to be gained in this by diving into the APIs of fundamental web technologies and popular frameworks?

(adapted and updated from an online talk presented at the [Hamburg VueJS meetup # 13](https://www.meetup.com/hamburg-vue-js-meetup/events/278870728/))

Presenter(s)
[Andrew Beng](https://github.com/andrewbeng89)

Presenter's bio
Software engineer currently focusing on frontend development for solutions in the news and media space for [Factorial](https://www.factorial.io/en/about-us), a digital agency based in Hamburg, Germany.

Duration
~20 minutes

Deck URL (if any)
[Learning by Experimenting](https://pitch.com/public/8e18a360-16c4-4b97-80a4-16cd4ccbfd46)

**Comment by tpiros** [comment]
Title of your topic
A picture is worth a thousand…kilobytes.

Topic description
A picture is in fact worth a thousand words, but it should not be worth a thousand kilobytes. In this talk we will take a look at tips and tricks that will enable you to deliver image heavy websites in a performant way. We will discuss the pros and cons of “next-gen” image formats, the various available loading methods and techniques and their effects on the Largest Contentful Paint and Cumulative Layout Shift Core Web Vital metrics. By the end of the talk you will be equipped with the right knowledge to deliver production sites with images that perform well to maximise user retention.

Presenter(s)
@tpiros

Presenter's bio
Tamas is a Google Developer Expert in Web Technologies and a seasoned Developer Evangelist. He is a passionate advocate for modern web technologies, helping people understand and unlock the latest & greatest features of web development.

Duration
~30

**Comment by tpiros** [comment]
hi @eriknguyen - is this event happening? I'd love to know because I'd prepare accordingly :) Thanks!

**Comment by joeytwiddle** [comment]
@tpiros Erik has been working on finding a venue. So i think he's keen to make it happen!

**Comment by tpiros** [comment]
Thanks @joeytwiddle - I will pencil in the date then. Please keep us updated re exact start time & venue :)

**Comment by tpiros** [comment]
hi @eriknguyen @joeytwiddle - any updates on the event for 22nd?

**Comment by eriknguyen** [comment]
@tpiros Sorry for the late update. Yes we're trying but struggling with the venue part again. Let me update you in a day or two for confirmation if that's ok.

Meanwhile, would you both be available on March 29 too, just to keep it as an option? @tpiros @andrewbeng89

**Comment by tpiros** [comment]
No worries. Unfortunately the 29th won’t work for me.

**Comment by notthetup** [comment]
@eriknguyen There's always HackerspaceSG as a backup if everything else fails. Between me, Sree or Valentine someone will be around to host at HackerspaceSG.

**Comment by eriknguyen** [comment]
Thank you all! The event is confirmed and published: https://www.meetup.com/singapore-js/events/292267655/ 
@tpiros @andrewbeng89 excited to have you 🚀

**Comment by andrewbeng89** [comment]
@eriknguyen unfortunately illness hasn't been kind to me and I've come down with a bad flu last night. I was very much looking forward to being there this evening, but will have to rain check this time.

**Comment by tpiros** [comment]
@andrewbeng89 wishing you a swift recovery!

@eriknguyen - are we still proceeding with the event? Please let me know in time if something changes.

**Comment by eriknguyen** [comment]
@tpiros Yes we're going to do it. But I won't be able to join today, so sorry I overbooked it. @joeytwiddle will be the main host :)

**Comment by eriknguyen** [comment]
@andrewbeng89 :( Take care friend! Hope to have you next month or something

**Comment by tpiros** [comment]
@eriknguyen @joeytwiddle - I’m at the venue but can’t get in - nobody is opening the door.

**Comment by joeytwiddle** [comment]
Here are the slides from @tpiros's talk on performant image delivery:

https://res.cloudinary.com/tamas-demo/image/upload/v1679536851/talks/singapore-js-22-03-23-a-picture-is-worth-a-1000-kilobytes.pdf

**Comment by joeytwiddle** [comment]
Thanks all!

**Comment by joeytwiddle** [comment]
Hi @andrewbeng89, would you be interested in speaking on 20th September? #55
