### ISSUE TITLE
talk.js - 2023 September

### ISSUE THREAD

**Issue by eriknguyen** [SingaporeJS/talk.js#55]
Meetup Event: TBA
Date: Wed, September 20
Hosts: TBC
Location: Rakuten Asia

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details open>
<summary>
Click for details

</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

**Comment by greentfrapp** [comment]
**Title of your topic**

How we built our own Generative Fill ([Reddit post with demo video](https://www.reddit.com/r/webdev/comments/15ikicx/showoff_saturday_our_homemade_generative_fill/))

**Topic description**

Lessons from building Generative Fill and developing a more visual way to interact with generative images

**Presenter(s)**

SK ([greentfrapp](https://github.com/greentfrapp))

**Presenter's bio**

Co-founder of [Pebblely](https://pebblely.com). Ex-Googler.

**Deck URL**

TBC

**Comment by joeytwiddle** [comment]
Thanks @greentfrapp, that looks really interesting! We would love to host your presentation in September.

**Comment by greentfrapp** [comment]
@joeytwiddle sure! Happy to present. Let me know more details re. timing once that's confirmed?

**Comment by eriknguyen** [comment]
Hi @greentfrapp Just want to confirm if you're good to go on Sep20?

**Comment by greentfrapp** [comment]
Hey @eriknguyen, may I know what time will this event be?

**Comment by eriknguyen** [comment]
@greentfrapp The main talks will start from 730pm tentatively. But we will gather people from 7pm for social

**Comment by greentfrapp** [comment]
Hi sure that works. I'll need to leave by 9pm but I'm good till then.

**Comment by trungk18** [comment]
Hello @eriknguyen @joeytwiddle, it's been a while since we last saw each other at talk.js. I still remember my debut talk at talk.js #39 three years ago. Hope to finally see you at an in-person talk soon.

**Title of your topic**

What's Next in Responsive Web Design?

**Topic description**

Transform your approach to responsive design with the power of modern CSS. Discover the game-changing features of container queries, style queries, and their seamless integration with CSS Grid. Get hands-on with user preference media features, allowing complete customization. Say goodbye to traditional media queries and embrace cutting-edge techniques to build dynamic and responsive websites. Join us on this exciting journey towards an intuitive, efficient, and adaptable future of responsiveness.

**Presenter(s)**

[@tuantrungvo](twitter.com/tuantrungvo)

**Presenter's bio**

https://trungk18.com/bio

**Duration**

I'll likely need about 30 minutes for the presentation since I currently have around 100 slides. However, I plan to trim down the content over the weekend to make it more concise.

**Deck URL (if any)**

I did present it at Google I/O Extended 2023 in Vietnam, the slide from this session can be found here.
https://trungk18.com/gdg23

**Comment by eriknguyen** [comment]
Awesome! Welcome back @trungk18. Super happy to have you again 🚀

**Comment by eriknguyen** [comment]
@greentfrapp Cool! That's great then. Thank you! I'll arrange your talk first so you can finish around 8pm+ :) And feel free to stay with us until the end or whenever you have to go 👌

**Comment by greentfrapp** [comment]
@eriknguyen That works! Thanks and see you then! Will add a link to the deck soon

**Comment by eriknguyen** [comment]
@greentfrapp @trungk18 the event page is up!! Feel free to let me know if you want to edit anything. If all good I'll hit announce tonight or tomorrow morning: https://www.meetup.com/singapore-js/events/295946098/

**Comment by greentfrapp** [comment]
LGTM, thanks @eriknguyen!

**Comment by eriknguyen** [comment]
@greentfrapp @trungk18 Hope you all enjoy your weekend and excited for this week!!

From our host at Rakuten:
> Regarding the AV set-up, we typically use Zoom to present and also do the recording. I understand that the event starts at 7 PM, but may I ask the speakers to come earlier at around 5.45 PM to do the AV testing? This is because our IT team usually goes off by 6 plus.

So would you mind coming early for that? Another option: I will definitely be there regardless, so if you don't mind presenting with my old MBP 13inch, I can do the AV test with my laptop and you can just come by at 7pm.

**Comment by eriknguyen** [comment]
Also, here are some of the questions the audiences left during registration that I've cleanup abit and organised here. The last part is abit vague btw.

#### Generative Art
    1. What are some of the trends you've seen over the last 6 months in Generative Art
    2. How did the Generative Art ideas started
    3. How will generative AI impact responsive web design
    4. Generative art - What is this technique used for in your project?
    5. what are the limitations of the art generated
    6. How to ensure we don’t infringe on other people’s IP.
    7. How do I explore what I can build with LLMs How do create my own chatbot for a given domain or business
    8. Is there any existing policies around the copyright of the item produced by the Generative Art?

#### Responsive Web
    1. What is the fastest way to do a responsive web ?
    2. Responsive Web Design, what's new?
    3. In responsive web dev, what’s the difference between doing a mobile-first design vs desktop-first design?
    4. How NextJs helps us build better applications with responsive design ?
    5. What are the key principles behind designing a responsive website?

#### Generic/both
    1. What new UX components will be needed for GenAI based applications?
    2. How can both co-exist?
    3. Have you heard of Bun? An alternative to NodeJS.
    4. what need to be learn to be ahead and get hired
    5. how as an individual I can support the team and learn more about this?

**Comment by greentfrapp** [comment]
Thanks @eriknguyen for the update and questions! If it's okay, I'm happy to present off your MBP and will be there by 7pm.

**Comment by trungk18** [comment]
@eriknguyen Thank you for the update. I actually planned to arrive early for technical testing, so I'll be able to make it on time. Looking forward to seeing you tomorrow!

**Comment by greentfrapp** [comment]
@eriknguyen I've updated my earliest comment above with the link to the slides - and linking here again for convenience - [LINK](https://docs.google.com/presentation/d/1JTnaJbWpaB0D3RnTB3oWctZWo0on9zw_n0Va7r2rB58/edit?usp=sharing)
See you tomorrow!

**Comment by eriknguyen** [comment]
Some more questions:
```<google-sheets-html-origin><style type="text/css"><!--td {border: 1px solid #cccccc;}br {mso-data-placement:same-cell;}--></style>

What are some popular algorithms or techniques used in generative art and some best practices for creating a responsive web design that works well across different devices and screen sizes
--
How do you think Gen Art and Responsive WebDev will change or continue to change industry standards and the everyday workflow?
Creative uses

```

**Comment by eriknguyen** [comment]
Here’s the Zoom details:

https://rakuten.zoom.us/j/97579653596?pwd=NVl4R1FwdisxM1FITnRidTZ1elBvUT09
Password: 015186

**Comment by trungk18** [comment]
Thank you for attending my talk at SingaporeJS. I hope you found them informative and helpful 🙂  As promised, I have included a link to my slides and some useful resources below for your reference. If you have any further questions or feedback, please don't hesitate to reach out. 

https://trungk18.com/talkjs23
