### ISSUE TITLE
talk.js - November 2023 (last one of the year)

### ISSUE THREAD

**Issue by eriknguyen** [SingaporeJS/talk.js#57]
Meetup Event: TBA
Date: Wed, November 15 (tentative)
Hosts: TBC
Location: TBC

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details open>
<summary>
Click for details

</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

**Comment by tsungtingdu** [comment]
Title of your topic

* Changing component’s behavior with a decorator

Topic description

* A decorator is a fundamental design pattern employed by Angular, serving as a pivotal tool for generating classes to fulfill various objectives. Additionally, we have the capability to craft our own decorators, enhancing our problem-solving abilities and simplifying our workflow. During this presentation, I will share how our team gradually introduced and deployed a style upgrade by utilizing a custom decorator and changing component behavior in Angular.

Presenter(s)

- Github: https://github.com/tsungtingdu
- Linkedin: https://www.linkedin.com/in/tsung-ting-tu/

Presenter's bio

* I am a Software Engineer at Ascenda Loyalty with three years of experience in Angular. I am passionate about solving problems through technology and collaborating with individuals from diverse backgrounds and areas of expertise. I enjoy sharing my knowledge and learning experiences with the team through various means.

Duration

* about 15 mins sharing

Deck URL (if any)
