### ISSUE TITLE
 talk.js - Feb 2024 

### ISSUE THREAD

**Issue by a-chocolate-bear** [SingaporeJS/talk.js#58]
Title of your topic

* GraphQL - Resolvers + Typescript = Magic

Topic description

* Building GraphQL servers can be frustrating and tedious. You have to write extra schema files, interfaces, and types for GraphQL fields and and arguments, write resolvers and then keep them in sync. You have to deal with type mismatches, typos, and refactoring issues. TypeScript functions already have all the information we need to generate a complete GraphQL API (including the schema and resolvers) using type annotations and docblock hints. This forms a single source of truth and completely eliminates the need for redundant boilerplate code. It lets you leverage the power of type inference to build type safe GraphQL APIs. In this demo, I will show you how to generate a complete GraphQL server using Hasura by writing only TypeScript functions that contain logic without building/writing API servers from scratch. This talk will change the way you think about building APIs with TypeScript. 

Presenter(s)

* Linkedin: https://www.linkedin.com/in/adamdmalone

Duration

* 25 minutes

**Comment by eriknguyen** [comment]
Hi @a-chocolate-bear , really sorry it's been awhile and we have been off, due to various life reasons :( 

I'm trying to host a talk coming August 13, in person. Would you be keen to give this talk now?
