### ISSUE TITLE
🎙 talk.js - January 2018

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/talk.js#6]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/245149764/)
- [x] Date: 24 January 2018 (Wednesday)
- [x] Hosts: @jsstrn
- [x] Venue: Microsoft, Level 21, One Marina Boulevard, Singapore 018989
- [ ] Deck: [talk.js - January]

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks
- [x] 150 Coding Challenges in 25 Days by _Yong Jun_
- [x] How I Built My First Self-Tracking App in React Native by _Mark Koester_
- [x] Running JavaScript on Microprocessors by _Iain Nash_

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability with @realsoelynn
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by realsoelynn** [comment]
@jsstrn i have booked the venue

**Comment by notthetup** [comment]
Wow this is early!

**Comment by jsstrn** [comment]
@notthetup It's one day before [JSConf.Asia](https://jsconf.asia). I figured that  a lot of people would be in Singapore during that period and it might for them to also attend talk.js.

Thank you @realsoelynn 😊

**Comment by notthetup** [comment]
#chope 😛

**Comment by yongjun21** [comment]
### Title of your talk

150 coding challenges in 25 days. What I learned from attempting Advent of Code 2017, 2016 & 2015 all at one go.

### Talk description

[Advent Of Code](http://adventofcode.com/) (AOC) is a series of small programming puzzles released released one per day over the Christmas period. I was introduced to AOC this year in 2017 and and was immediately hooked. I decided to challenged myself to complete not just this year's AOC but the two previous years all at one go. After spending 25 days of Christmas in programming hell, I emerged a true JavaScript Jedi. This talk shares my learning from this experience and tips for fellow JavaScript Jedi (and Ninja) to acing their next technical interview.

### Presenter(s)

[Yong Jun](https://github.com/yongjun21)

### A short introduction of yourself

JavaScript Ninja working on software for public good

### 20+min
 
### Deck URL (if any)

You can add this part in later

**Comment by jsstrn** [comment]
@yongjun21 This is so cool! Can't wait! 🎉

**Comment by yosriady** [comment]
**Title of your talk**

Alternative State Management with React + MobX

**Talk description**

MobX is a battle tested library that makes state management simple and scalable by transparently applying functional reactive programming (TFRP). In this talk, you'll learn the core concepts of MobX and what this alternative to Redux offers for modern frontend applications.

**Presenter**

[Yos Riady](https://yos.io/about)

**Deck URL**

[Still in progress, but will be here](https://goo.gl/7V8Pto)

**Comment by yosriady** [comment]
@jsstrn

**Comment by jsstrn** [comment]
@ yosriady I received an email notification about your proposed talk on **Alternative State Management with React + MobX** but I don't see that here. Did I miss something?

**Comment by yosriady** [comment]
@jsstrn I decided to postpone the talk for now, thanks!

**Comment by markwk** [comment]
Title of your talk

**PhotoStats.io: How I Built My First Self-Tracking App in React Native (and what I learned)**

Talk description

In early 2017, I started studying react native but without a specific project in mind. Towards the end of 2017, I got inspired to build a quantified self / self-tracking app about my photos. I wanted to know more about my photo data, my trends, and what this data my tell me. 

The result was [PhotoStats.io](www.photostats.io), which lets you track, visualize, and learn from your photo data. 

In this talk I'll share what I've learned about react native, photo data, building cross-platform apps, some good libraries and resources, and, of course, tips for anyone else getting started using react native to build apps. 

Presenter: 

[Mark Koester](http://www.markwk.com)

A short introduction of yourself:

"Recovering" Drupal, PHP and Open-Source Developer with an active interest in javascript, react native, data science and the quantified self. Blogs @ [www.markwk.com](http://www.markwk.com). Founder / Operator @ [Int3c.com](http://int3c.com) 

Duration: 
20-30 min (but could be shorter or longer as needed)

**Comment by iainnash** [comment]
Title of your talk:
**Running Javascript on Microprocessors**

Talk description:
Many new wireless-embedded small ARM development boards have been coming out recently at really affordable prices. Many of these boards can run a stripped down javascript execution environment. This opens up development beyond less flexible, lower-level static and compiled languages increasing speed and accessibility for more developers.
This talk will cover Mongoose OS and Espruino on an ESP32 development board and on a ESP8266 Development Board. We will go from setting up the development environment on a fresh board, reading documentation, and creating a simple temperature sensor and doorbell device running a web server over WIFI.

Presenter:
@iainnash

Presenter's bio:
A New-York based software engineering who enjoys building Internet of Things devices and tinkering with microprocessors in his spare time. Working at Oscar Health to make insurance more accessible.

Duration requested:
20min

**Comment by jsstrn** [comment]
@yongjun21 @markwk @iainnash Hi speakers, thanks for submitting your talks. Please keep your talks to 20 min as we have 3 speakers.

Please also note that our usual venue at PayPal is not available this month (due to renovation) and we will need to change the venue. I will update the venue once I have confirmed a new location.

**Comment by yoshuawuyts** [comment]
@jsstrn is there still an option to submit talks? If possible I'd love to submit one!

**Comment by jsstrn** [comment]
Please note that there is a change in venue for this month's event. We will be hosting the event at Microsoft instead. 

The address is:
Microsoft
Level 21, One Marina Boulevard,
Singapore 018989

You may use Citymapper to help you find your way [there](https://citymapper.com/go/mexg16)

**Comment by jsstrn** [comment]
@yoshuawuyts thanks for your interest in submitting your talk to talk.js.

Speaker line up is full for this month. I hope you will consider submitting your talk for next month (see #9 for February and #10 for March). I hope to see you then 👋

**Comment by yoshuawuyts** [comment]
@jsstrn ah bummer, thanks for your reply! ✨

**Comment by sebdeckers** [comment]
Thanks for another nice event, everyone. Great to have many visitors in attendance due to JSConf.Asia.

Videos were uploaded almost immediately. Links for reference:
- https://engineers.sg/video/150-coding-challenges-in-25-days-talk-js--2247
- https://engineers.sg/video/how-i-built-my-first-self-tracking-app-in-react-native-talk-js--2246
- https://engineers.sg/video/running-javascript-on-microprocessors-talk-js--2248
