### ISSUE TITLE
🎙 talk.js - February 2018

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/talk.js#9]
### 📝 Details
- [ ] Event: [talk.js]()
- [x] Date: 21 February 2018 (Wednesday)
- [x] Hosts: @jsstrn
- [x] Venue: Microsoft, Level 21, One Marina Boulevard, Singapore 018989

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks
- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your talk
> Insert catchy title here
>
> #### Talk description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration requested
> 10min, 20min, 30min
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability with @realsoelynn
- [ ] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [ ] Inform @engineersftw for video recordings
- [ ] Announce event and update channel description on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by sebdeckers** [comment]
@jsstrn Long ago I accidentally created a Meetup draft event for December. Not sure how to delete it, but it can also be renamed to the February slot.

**Comment by jsstrn** [comment]
No speakers yet - still celebrating Chinese New Year 🍊🍊
